trigger:
- master
- rel/*

queue: Hosted VS2017
variables: 
  BuildConfiguration: Release
steps:
- template: .vsts-shared.yml
  parameters:
    signSteps:
    - task: PowerShell@2
      displayName: Authenticode Sign artifacts
      inputs:
        filePath: scripts/Sign-Package.ps1
      env:
        SignClientUser: $(SignClientUser)
        SignClientSecret: $(SignClientSecret)
        ArtifactDirectory: $(Build.ArtifactStagingDirectory)\Packages
