parameters: 
  signSteps: []
  
steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: '2.1.400-preview-008975'

- task: NuGetToolInstaller@0
  displayName: Use NuGet 4.7.0
  inputs:
    versionSpec: 4.7.0

- task: DotNetCoreCLI@2
  inputs:
    command: build
    projects: scripts/setversion.csproj
    arguments: -c $(BuildConfiguration)   
  displayName: Set Version
  condition: eq(variables['system.pullrequest.isfork'], false)
 
- task: DotNetCoreCLI@2
  inputs:
    command: build
    projects: .\src\Humanizer.sln
    arguments: -c $(BuildConfiguration)   
  displayName: Build  
  
- powershell: |
    mkdir $(Build.ArtifactStagingDirectory)\Packages
    # version    
    nuget install NerdBank.GitVersioning -SolutionDir $(Build.SourcesDirectory) -Verbosity quiet -ExcludeVersion    
    $vers = & $(Build.SourcesDirectory)\packages\nerdbank.gitversioning\tools\Get-Version.ps1
    $nugetVer = $vers.NuGetPackageVersion  
    $commitId = $vers.GitCommitId 
    
    ls .\NuSpecs\*.nuspec | %{ nuget pack $_.FullName -version "$nugetVer" -BasePath "src" -NoPackageAnalysis -OutputDirectory $(Build.ArtifactStagingDirectory)\Packages -Properties "RepositoryType=git;RepositoryCommit=$commitId;RepositoryUrl=https://github.com/Humanizr/Humanizer"}
  displayName: Create packages
  
- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: .\src\Humanizer.Tests\Humanizer.Tests.csproj
    arguments: -c $(BuildConfiguration) --collect:"Code Coverage" -s $(System.DefaultWorkingDirectory)/src/CodeCoverage.runsettings /p:DebugType=portable
  displayName: Run Tests
  
- ${{ parameters.signSteps }}

- task: PublishBuildArtifacts@1
  displayName: Publish Package Artifacts
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)\Packages
    artifactType: container
    artifactName: Packages
  condition: eq(variables['system.pullrequest.isfork'], false)
  