namespace ruRU;

[UseCulture("ru-RU")]
public class HeadingTests
{
    [InlineData(0, "С")]
    [InlineData(11.2, "С")]
    [InlineData(11.3, "ССВ")]
    [InlineData(22.5, "ССВ")]
    [InlineData(33.7, "ССВ")]
    [InlineData(33.8, "СВ")]
    [InlineData(45, "СВ")]
    [InlineData(56.2, "СВ")]
    [InlineData(56.3, "ВСВ")]
    [InlineData(67.5, "ВСВ")]
    [InlineData(78.7, "ВСВ")]
    [InlineData(78.8, "В")]
    [InlineData(90, "В")]
    [InlineData(101.2, "В")]
    [InlineData(101.3, "ВЮВ")]
    [InlineData(112.5, "ВЮВ")]
    [InlineData(123.7, "ВЮВ")]
    [InlineData(123.8, "ЮВ")]
    [InlineData(135, "ЮВ")]
    [InlineData(146.2, "ЮВ")]
    [InlineData(146.3, "ЮЮВ")]
    [InlineData(157.5, "ЮЮВ")]
    [InlineData(168.7, "ЮЮВ")]
    [InlineData(168.8, "Ю")]
    [InlineData(180, "Ю")]
    [InlineData(191.2, "Ю")]
    [InlineData(191.3, "ЮЮЗ")]
    [InlineData(202.5, "ЮЮЗ")]
    [InlineData(213.7, "ЮЮЗ")]
    [InlineData(213.8, "ЮЗ")]
    [InlineData(225, "ЮЗ")]
    [InlineData(236.2, "ЮЗ")]
    [InlineData(236.3, "ЗЮЗ")]
    [InlineData(247.5, "ЗЮЗ")]
    [InlineData(258.7, "ЗЮЗ")]
    [InlineData(258.8, "З")]
    [InlineData(270, "З")]
    [InlineData(281.2, "З")]
    [InlineData(281.3, "ЗСЗ")]
    [InlineData(292.5, "ЗСЗ")]
    [InlineData(303.7, "ЗСЗ")]
    [InlineData(303.8, "СЗ")]
    [InlineData(315, "СЗ")]
    [InlineData(326.2, "СЗ")]
    [InlineData(326.3, "ССЗ")]
    [InlineData(337.5, "ССЗ")]
    [InlineData(348.7, "ССЗ")]
    [InlineData(348.8, "С")]
    [InlineData(360, "С")]
    [InlineData(720, "С")]
    [Theory]
    public void ToHeadingAbbreviated(double heading, string expected) =>
        Assert.Equal(expected, heading.ToHeading());

    [InlineData(0, "север")]
    [InlineData(22.5, "северо-северо-восток")]
    [InlineData(45, "северо-восток")]
    [InlineData(67.5, "востоко-северо-восток")]
    [InlineData(90, "восток")]
    [InlineData(112.5, "востоко-юго-восток")]
    [InlineData(135, "юго-восток")]
    [InlineData(157.5, "юго-юго-восток")]
    [InlineData(180, "юг")]
    [InlineData(202.5, "юго-юго-запад")]
    [InlineData(225, "юго-запад")]
    [InlineData(247.5, "западо-юго-запад")]
    [InlineData(270, "запад")]
    [InlineData(292.5, "западо-северо-запад")]
    [InlineData(315, "северо-запад")]
    [InlineData(337.5, "северо-северо-запад")]
    [InlineData(360, "север")]
    [InlineData(720, "север")]
    [Theory]
    public void ToHeading(double heading, string expected) =>
        Assert.Equal(expected, heading.ToHeading(HeadingStyle.Full));

    [InlineData("С", 0)]
    [InlineData("ССВ", 22.5)]
    [InlineData("СВ", 45)]
    [InlineData("ВСВ", 67.5)]
    [InlineData("В", 90)]
    [InlineData("ВЮВ", 112.5)]
    [InlineData("ЮВ", 135)]
    [InlineData("ЮЮВ", 157.5)]
    [InlineData("Ю", 180)]
    [InlineData("ЮЮЗ", 202.5)]
    [InlineData("ЮЗ", 225)]
    [InlineData("ЗЮЗ", 247.5)]
    [InlineData("З", 270)]
    [InlineData("ЗСЗ", 292.5)]
    [InlineData("СЗ", 315)]
    [InlineData("ССЗ", 337.5)]
    [Theory]
    public void FromShortHeading(string heading, double expected) =>
        Assert.Equal(expected, heading.FromAbbreviatedHeading());
}