namespace Humanizer;

static class TokenMapWordsToNumberConverters
{
    public static IWordsToNumberConverter Afrikaans { get; } = new TokenMapWordsToNumberConverter(new()
    {
        CardinalMap = new Dictionary<string, long>(StringComparer.Ordinal)
        {
            ["nul"] = 0,
            ["een"] = 1,
            ["twee"] = 2,
            ["drie"] = 3,
            ["vier"] = 4,
            ["vyf"] = 5,
            ["ses"] = 6,
            ["sewe"] = 7,
            ["agt"] = 8,
            ["nege"] = 9,
            ["tien"] = 10,
            ["elf"] = 11,
            ["twaalf"] = 12,
            ["dertien"] = 13,
            ["veertien"] = 14,
            ["vyftien"] = 15,
            ["sestien"] = 16,
            ["sewentien"] = 17,
            ["agtien"] = 18,
            ["negentien"] = 19,
            ["twintig"] = 20,
            ["dertig"] = 30,
            ["veertig"] = 40,
            ["vyftig"] = 50,
            ["sestig"] = 60,
            ["sewentig"] = 70,
            ["tagtig"] = 80,
            ["negentig"] = 90,
            ["honderd"] = 100,
            ["duisend"] = 1_000,
            ["miljoen"] = 1_000_000,
            ["miljard"] = 1_000_000_000
        }.ToFrozenDictionary(StringComparer.Ordinal),
        NormalizationProfile = TokenMapNormalizationProfile.LowercaseRemovePeriods,
        NegativePrefixes = ["minus "],
        IgnoredTokens = ["en"],
        UseHundredMultiplier = true
    });

    public static IWordsToNumberConverter Armenian { get; } = new TokenMapWordsToNumberConverter(new()
    {
        CardinalMap = new Dictionary<string, long>(StringComparer.Ordinal)
        {
            ["զրո"] = 0,
            ["մեկ"] = 1,
            ["երկու"] = 2,
            ["երեք"] = 3,
            ["չորս"] = 4,
            ["հինգ"] = 5,
            ["վեց"] = 6,
            ["յոթ"] = 7,
            ["ութ"] = 8,
            ["ինը"] = 9,
            ["տաս"] = 10,
            ["տասնմեկ"] = 11,
            ["տասներկու"] = 12,
            ["տասներեք"] = 13,
            ["տասնչորս"] = 14,
            ["տասնհինգ"] = 15,
            ["տասնվեց"] = 16,
            ["տասնյոթ"] = 17,
            ["տասնութ"] = 18,
            ["տասնինը"] = 19,
            ["քսան"] = 20,
            ["երեսուն"] = 30,
            ["քառասուն"] = 40,
            ["հիսուն"] = 50,
            ["վաթսուն"] = 60,
            ["յոթանասուն"] = 70,
            ["ութսուն"] = 80,
            ["իննսուն"] = 90,
            ["հարյուր"] = 100,
            ["հազար"] = 1_000,
            ["միլիոն"] = 1_000_000,
            ["միլիարդ"] = 1_000_000_000
        }.ToFrozenDictionary(StringComparer.Ordinal),
        NormalizationProfile = TokenMapNormalizationProfile.CollapseWhitespace,
        NegativePrefixes = ["մինուս "],
        UseHundredMultiplier = true
    });

    public static IWordsToNumberConverter Bulgarian { get; } = new TokenMapWordsToNumberConverter(new()
    {
        CardinalMap = new Dictionary<string, long>(StringComparer.Ordinal)
        {
            ["нула"] = 0,
            ["един"] = 1,
            ["една"] = 1,
            ["едно"] = 1,
            ["два"] = 2,
            ["две"] = 2,
            ["три"] = 3,
            ["четири"] = 4,
            ["пет"] = 5,
            ["шест"] = 6,
            ["седем"] = 7,
            ["осем"] = 8,
            ["девет"] = 9,
            ["десет"] = 10,
            ["единадесет"] = 11,
            ["дванадесет"] = 12,
            ["дванайсет"] = 12,
            ["тринадесет"] = 13,
            ["тринайсет"] = 13,
            ["четиринадесет"] = 14,
            ["четиринайсет"] = 14,
            ["петнадесет"] = 15,
            ["петнайсет"] = 15,
            ["шестнадесет"] = 16,
            ["шестнайсет"] = 16,
            ["седемнадесет"] = 17,
            ["седемнайсет"] = 17,
            ["осемнадесет"] = 18,
            ["осемнайсет"] = 18,
            ["деветнадесет"] = 19,
            ["деветнайсет"] = 19,
            ["двадесет"] = 20,
            ["двайсет"] = 20,
            ["тридесет"] = 30,
            ["трийсет"] = 30,
            ["четиридесет"] = 40,
            ["петдесет"] = 50,
            ["шестдесет"] = 60,
            ["седемдесет"] = 70,
            ["осемдесет"] = 80,
            ["деветдесет"] = 90,
            ["сто"] = 100,
            ["двеста"] = 200,
            ["триста"] = 300,
            ["четиристотин"] = 400,
            ["петстотин"] = 500,
            ["шестстотин"] = 600,
            ["седемстотин"] = 700,
            ["осемстотин"] = 800,
            ["деветстотин"] = 900,
            ["хиляда"] = 1_000,
            ["хиляди"] = 1_000,
            ["милион"] = 1_000_000,
            ["милиона"] = 1_000_000,
            ["милиард"] = 1_000_000_000,
            ["милиарда"] = 1_000_000_000,
            ["трилион"] = 1_000_000_000_000,
            ["трилиона"] = 1_000_000_000_000,
            ["квадрилион"] = 1_000_000_000_000_000,
            ["квадрилиона"] = 1_000_000_000_000_000,
            ["квинтилион"] = 1_000_000_000_000_000_000,
            ["квинтилиона"] = 1_000_000_000_000_000_000
        }.ToFrozenDictionary(StringComparer.Ordinal),
        NormalizationProfile = TokenMapNormalizationProfile.LowercaseReplacePeriodsWithSpaces,
        NegativePrefixes = ["минус "],
        IgnoredTokens = ["и"],
        AllowInvariantIntegerInput = true
    });

    public static IWordsToNumberConverter Bengali { get; } = new TokenMapWordsToNumberConverter(new()
    {
        CardinalMap = new Dictionary<string, long>(StringComparer.Ordinal)
        {
            ["শূন্য"] = 0,
            ["এক"] = 1,
            ["দুই"] = 2,
            ["তিন"] = 3,
            ["চার"] = 4,
            ["পাঁচ"] = 5,
            ["ছয়"] = 6,
            ["সাত"] = 7,
            ["আট"] = 8,
            ["নয়"] = 9,
            ["দশ"] = 10,
            ["এগারো"] = 11,
            ["বারো"] = 12,
            ["বিশ"] = 20,
            ["একুশ"] = 21,
            ["বাইশ"] = 22,
            ["তেইশ"] = 23,
            ["নব্বই"] = 90,
            ["একশ"] = 100,
            ["দুইশ"] = 200,
            ["তিনশ"] = 300,
            ["চারশ"] = 400,
            ["পাঁচশ"] = 500,
            ["ছয়শ"] = 600,
            ["সাতশ"] = 700,
            ["আটশ"] = 800,
            ["এক হাজার"] = 1_000,
            ["হাজার"] = 1_000,
            ["লক্ষ"] = 100_000,
            ["কোটি"] = 10_000_000,
            ["চৌঁতিরিশ"] = 34,
            ["পঁয়তাল্লিশ"] = 45,
            ["ছাপ্পান্ন"] = 56,
            ["সাতষট্টি"] = 67,
            ["আটাত্তর"] = 78,
            ["উননব্বই"] = 99
        }.ToFrozenDictionary(StringComparer.Ordinal),
        NormalizationProfile = TokenMapNormalizationProfile.CollapseWhitespace,
        NegativePrefixes = ["ঋণাত্মক "]
    });

    public static IWordsToNumberConverter Catalan { get; } = new TokenMapWordsToNumberConverter(new()
    {
        CardinalMap = new Dictionary<string, long>(StringComparer.Ordinal)
        {
            ["zero"] = 0,
            ["un"] = 1,
            ["u"] = 1,
            ["una"] = 1,
            ["dos"] = 2,
            ["dues"] = 2,
            ["tres"] = 3,
            ["quatre"] = 4,
            ["cinc"] = 5,
            ["sis"] = 6,
            ["set"] = 7,
            ["vuit"] = 8,
            ["nou"] = 9,
            ["deu"] = 10,
            ["onze"] = 11,
            ["dotze"] = 12,
            ["tretze"] = 13,
            ["catorze"] = 14,
            ["quinze"] = 15,
            ["setze"] = 16,
            ["disset"] = 17,
            ["divuit"] = 18,
            ["dinou"] = 19,
            ["vint"] = 20,
            ["trenta"] = 30,
            ["quaranta"] = 40,
            ["cinquanta"] = 50,
            ["seixanta"] = 60,
            ["setanta"] = 70,
            ["vuitanta"] = 80,
            ["noranta"] = 90,
            ["cent"] = 100,
            ["cents"] = 100,
            ["centes"] = 100,
            ["mil"] = 1000,
            ["milió"] = 1_000_000,
            ["milions"] = 1_000_000
        }.ToFrozenDictionary(StringComparer.Ordinal),
        OrdinalMap = BuildCatalanOrdinalMap(),
        NormalizationProfile = TokenMapNormalizationProfile.LowercaseRemovePeriods,
        NegativePrefixes = ["menys "],
        IgnoredTokens = ["i"],
        OrdinalAbbreviationSuffixes = ["r", "n", "a", "è"],
        UseHundredMultiplier = true
    });

    public static IWordsToNumberConverter Croatian { get; } = new TokenMapWordsToNumberConverter(new()
    {
        CardinalMap = new Dictionary<string, long>(StringComparer.Ordinal)
        {
            ["nula"] = 0,
            ["jedan"] = 1,
            ["jedna"] = 1,
            ["jedno"] = 1,
            ["dva"] = 2,
            ["dvije"] = 2,
            ["tri"] = 3,
            ["četiri"] = 4,
            ["cetiri"] = 4,
            ["pet"] = 5,
            ["šest"] = 6,
            ["sest"] = 6,
            ["sedam"] = 7,
            ["osam"] = 8,
            ["devet"] = 9,
            ["deset"] = 10,
            ["jedanaest"] = 11,
            ["dvanaest"] = 12,
            ["trinaest"] = 13,
            ["četrnaest"] = 14,
            ["cetrnaest"] = 14,
            ["petnaest"] = 15,
            ["šesnaest"] = 16,
            ["sesnaest"] = 16,
            ["sedamnaest"] = 17,
            ["osamnaest"] = 18,
            ["devetnaest"] = 19,
            ["dvadeset"] = 20,
            ["trideset"] = 30,
            ["četrdeset"] = 40,
            ["cetrdeset"] = 40,
            ["pedeset"] = 50,
            ["šezdeset"] = 60,
            ["sezdeset"] = 60,
            ["sedamdeset"] = 70,
            ["osamdeset"] = 80,
            ["devedeset"] = 90,
            ["sto"] = 100,
            ["dvjesto"] = 200,
            ["tristo"] = 300,
            ["četiristo"] = 400,
            ["cetiristo"] = 400,
            ["petsto"] = 500,
            ["šeststo"] = 600,
            ["seststo"] = 600,
            ["sedamsto"] = 700,
            ["osamsto"] = 800,
            ["devetsto"] = 900,
            ["tisuću"] = 1_000,
            ["tisucu"] = 1_000,
            ["tisuće"] = 1_000,
            ["tisuce"] = 1_000,
            ["tisuća"] = 1_000,
            ["tisuca"] = 1_000,
            ["milijun"] = 1_000_000,
            ["milijuna"] = 1_000_000,
            ["milijarda"] = 1_000_000_000,
            ["milijarde"] = 1_000_000_000,
            ["milijardi"] = 1_000_000_000
        }.ToFrozenDictionary(StringComparer.Ordinal),
        NormalizationProfile = TokenMapNormalizationProfile.LowercaseRemovePeriods,
        NegativePrefixes = ["minus "]
    });

    public static IWordsToNumberConverter Czech { get; } = new TokenMapWordsToNumberConverter(new()
    {
        CardinalMap = new Dictionary<string, long>(StringComparer.Ordinal)
        {
            ["nula"] = 0,
            ["jeden"] = 1,
            ["jedna"] = 1,
            ["jedno"] = 1,
            ["dva"] = 2,
            ["dvě"] = 2,
            ["dve"] = 2,
            ["tři"] = 3,
            ["tri"] = 3,
            ["čtyři"] = 4,
            ["ctyri"] = 4,
            ["pět"] = 5,
            ["pet"] = 5,
            ["šest"] = 6,
            ["sest"] = 6,
            ["sedm"] = 7,
            ["osm"] = 8,
            ["devět"] = 9,
            ["devet"] = 9,
            ["deset"] = 10,
            ["jedenáct"] = 11,
            ["jedenact"] = 11,
            ["dvanáct"] = 12,
            ["dvanact"] = 12,
            ["třináct"] = 13,
            ["trinact"] = 13,
            ["čtrnáct"] = 14,
            ["ctrnact"] = 14,
            ["patnáct"] = 15,
            ["patnact"] = 15,
            ["šestnáct"] = 16,
            ["sestnact"] = 16,
            ["sedmnáct"] = 17,
            ["sedmnact"] = 17,
            ["osmnáct"] = 18,
            ["osmnact"] = 18,
            ["devatenáct"] = 19,
            ["devatenact"] = 19,
            ["dvacet"] = 20,
            ["třicet"] = 30,
            ["tricet"] = 30,
            ["čtyřicet"] = 40,
            ["ctyricet"] = 40,
            ["padesát"] = 50,
            ["padesat"] = 50,
            ["šedesát"] = 60,
            ["sedmdesát"] = 70,
            ["sedmdesat"] = 70,
            ["osmdesát"] = 80,
            ["osmdesat"] = 80,
            ["devadesát"] = 90,
            ["devadesat"] = 90,
            ["sto"] = 100,
            ["sta"] = 100,
            ["set"] = 100,
            ["tisíc"] = 1_000,
            ["tisic"] = 1_000,
            ["tisíce"] = 1_000,
            ["tisice"] = 1_000,
            ["milion"] = 1_000_000,
            ["miliony"] = 1_000_000,
            ["milionů"] = 1_000_000,
            ["milionu"] = 1_000_000,
            ["miliarda"] = 1_000_000_000,
            ["miliardy"] = 1_000_000_000
        }.ToFrozenDictionary(StringComparer.Ordinal),
        NormalizationProfile = TokenMapNormalizationProfile.LowercaseRemovePeriods,
        NegativePrefixes = ["mínus ", "minus "],
        UseHundredMultiplier = true
    });

    public static IWordsToNumberConverter Greek { get; } = new TokenMapWordsToNumberConverter(new()
    {
        CardinalMap = new Dictionary<string, long>(StringComparer.Ordinal)
        {
            ["ένα"] = 1,
            ["ενα"] = 1,
            ["ένας"] = 1,
            ["ενας"] = 1,
            ["μία"] = 1,
            ["μια"] = 1,
            ["δύο"] = 2,
            ["δυο"] = 2,
            ["τρία"] = 3,
            ["τρια"] = 3,
            ["τρείς"] = 3,
            ["τρεις"] = 3,
            ["τέσσερα"] = 4,
            ["τεσσερα"] = 4,
            ["πέντε"] = 5,
            ["πεντε"] = 5,
            ["έξι"] = 6,
            ["εξι"] = 6,
            ["επτά"] = 7,
            ["επτα"] = 7,
            ["οκτώ"] = 8,
            ["οκτω"] = 8,
            ["εννέα"] = 9,
            ["εννεα"] = 9,
            ["δέκα"] = 10,
            ["δεκα"] = 10,
            ["έντεκα"] = 11,
            ["εντεκα"] = 11,
            ["δώδεκα"] = 12,
            ["δωδεκα"] = 12,
            ["δεκατρείς"] = 13,
            ["δεκατρεις"] = 13,
            ["δεκατέσσερα"] = 14,
            ["δεκατεσσερα"] = 14,
            ["είκοσι"] = 20,
            ["εικοσι"] = 20,
            ["τριάντα"] = 30,
            ["τριαντα"] = 30,
            ["σαράντα"] = 40,
            ["σαραντα"] = 40,
            ["πενήντα"] = 50,
            ["πενηντα"] = 50,
            ["εξήντα"] = 60,
            ["εξηντα"] = 60,
            ["εβδομήντα"] = 70,
            ["εβδομηντα"] = 70,
            ["ογδόντα"] = 80,
            ["ογδοντα"] = 80,
            ["ενενήντα"] = 90,
            ["ενενηντα"] = 90,
            ["εκατό"] = 100,
            ["εκατο"] = 100,
            ["εκατόν"] = 100,
            ["εκατον"] = 100,
            ["διακόσια"] = 200,
            ["διακοσια"] = 200,
            ["τριακόσια"] = 300,
            ["τριακοσια"] = 300,
            ["τετρακόσια"] = 400,
            ["τετρακοσια"] = 400,
            ["πεντακόσια"] = 500,
            ["πεντακοσια"] = 500,
            ["εξακόσια"] = 600,
            ["εξακοσια"] = 600,
            ["επτακόσια"] = 700,
            ["επτακοσια"] = 700,
            ["οκτακόσια"] = 800,
            ["οκτακοσια"] = 800,
            ["εννιακόσια"] = 900,
            ["εννιακοσια"] = 900,
            ["χίλια"] = 1_000,
            ["χιλια"] = 1_000,
            ["χιλιάδες"] = 1_000,
            ["χιλιαδες"] = 1_000,
            ["εκατομμύριο"] = 1_000_000,
            ["εκατομμυριο"] = 1_000_000,
            ["εκατομμύρια"] = 1_000_000,
            ["εκατομμυρια"] = 1_000_000,
            ["δισεκατομμύριο"] = 1_000_000_000,
            ["δισεκατομμυριο"] = 1_000_000_000,
            ["δισεκατομμύρια"] = 1_000_000_000,
            ["δισεκατομμυρια"] = 1_000_000_000
        }.ToFrozenDictionary(StringComparer.Ordinal),
        NormalizationProfile = TokenMapNormalizationProfile.LowercaseRemovePeriods
    });

    public static IWordsToNumberConverter Latvian { get; } = new TokenMapWordsToNumberConverter(new()
    {
        CardinalMap = new Dictionary<string, long>(StringComparer.Ordinal)
        {
            ["viens"] = 1,
            ["divi"] = 2,
            ["trīs"] = 3,
            ["tris"] = 3,
            ["četri"] = 4,
            ["cetri"] = 4,
            ["pieci"] = 5,
            ["seši"] = 6,
            ["sesi"] = 6,
            ["septiņi"] = 7,
            ["septini"] = 7,
            ["astoņi"] = 8,
            ["astoni"] = 8,
            ["deviņi"] = 9,
            ["devini"] = 9,
            ["desmit"] = 10,
            ["vienpadsmit"] = 11,
            ["divpadsmit"] = 12,
            ["trīspadsmit"] = 13,
            ["trispadsmit"] = 13,
            ["četrpadsmit"] = 14,
            ["cetrpadsmit"] = 14,
            ["piecpadsmit"] = 15,
            ["sešpadsmit"] = 16,
            ["sespadsmit"] = 16,
            ["septiņpadsmit"] = 17,
            ["septinpadsmit"] = 17,
            ["astoņpadsmit"] = 18,
            ["astonpadsmit"] = 18,
            ["deviņpadsmit"] = 19,
            ["devinpadsmit"] = 19,
            ["divdesmit"] = 20,
            ["trīsdesmit"] = 30,
            ["trisdesmit"] = 30,
            ["četrdesmit"] = 40,
            ["cetrdesmit"] = 40,
            ["piecdesmit"] = 50,
            ["sešdesmit"] = 60,
            ["sesdesmit"] = 60,
            ["septiņdesmit"] = 70,
            ["septindesmit"] = 70,
            ["astoņdesmit"] = 80,
            ["astondesmit"] = 80,
            ["deviņdesmit"] = 90,
            ["devindesmit"] = 90,
            ["simts"] = 100,
            ["simtu"] = 100,
            ["simti"] = 100,
            ["tūkstotis"] = 1_000,
            ["tukstotis"] = 1_000,
            ["tūkstoš"] = 1_000,
            ["tukstos"] = 1_000,
            ["tūkstoši"] = 1_000,
            ["tukstosi"] = 1_000,
            ["miljons"] = 1_000_000,
            ["miljoni"] = 1_000_000
        }.ToFrozenDictionary(StringComparer.Ordinal),
        NormalizationProfile = TokenMapNormalizationProfile.LowercaseRemovePeriods,
        UseHundredMultiplier = true
    });

    public static IWordsToNumberConverter Lithuanian { get; } = new TokenMapWordsToNumberConverter(new()
    {
        CardinalMap = new Dictionary<string, long>(StringComparer.Ordinal)
        {
            ["nulis"] = 0,
            ["vienas"] = 1,
            ["viena"] = 1,
            ["du"] = 2,
            ["dvi"] = 2,
            ["trys"] = 3,
            ["keturi"] = 4,
            ["keturios"] = 4,
            ["penki"] = 5,
            ["penkios"] = 5,
            ["šeši"] = 6,
            ["sesi"] = 6,
            ["šešios"] = 6,
            ["sesios"] = 6,
            ["septyni"] = 7,
            ["septynios"] = 7,
            ["aštuoni"] = 8,
            ["astuoni"] = 8,
            ["aštuonios"] = 8,
            ["astuonios"] = 8,
            ["devyni"] = 9,
            ["devynios"] = 9,
            ["dešimt"] = 10,
            ["desimt"] = 10,
            ["vienuolika"] = 11,
            ["dvylika"] = 12,
            ["trylika"] = 13,
            ["keturiolika"] = 14,
            ["penkiolika"] = 15,
            ["šešiolika"] = 16,
            ["sesiolika"] = 16,
            ["septyniolika"] = 17,
            ["aštuoniolika"] = 18,
            ["astuoniolika"] = 18,
            ["devyniolika"] = 19,
            ["dvidešimt"] = 20,
            ["dvidesimt"] = 20,
            ["trisdešimt"] = 30,
            ["trisdesimt"] = 30,
            ["keturiasdešimt"] = 40,
            ["keturiasdesimt"] = 40,
            ["penkiasdešimt"] = 50,
            ["penkiasdesimt"] = 50,
            ["šešiasdešimt"] = 60,
            ["sesiasdesimt"] = 60,
            ["septyniasdešimt"] = 70,
            ["septyniasdesimt"] = 70,
            ["aštuoniasdešimt"] = 80,
            ["astuoniasdesimt"] = 80,
            ["devyniasdešimt"] = 90,
            ["devyniasdesimt"] = 90,
            ["šimtas"] = 100,
            ["simtas"] = 100,
            ["šimtai"] = 100,
            ["simtai"] = 100,
            ["tūkstantis"] = 1_000,
            ["tukstantis"] = 1_000,
            ["tūkstančiai"] = 1_000,
            ["tukstanciai"] = 1_000,
            ["tūkstančių"] = 1_000,
            ["tukstanciu"] = 1_000,
            ["milijonas"] = 1_000_000,
            ["milijonai"] = 1_000_000,
            ["milijonų"] = 1_000_000,
            ["milijonu"] = 1_000_000
        }.ToFrozenDictionary(StringComparer.Ordinal),
        NormalizationProfile = TokenMapNormalizationProfile.LowercaseRemovePeriods,
        NegativePrefixes = ["minus "],
        UseHundredMultiplier = true
    });

    public static IWordsToNumberConverter Polish { get; } = new TokenMapWordsToNumberConverter(new()
    {
        CardinalMap = new Dictionary<string, long>(StringComparer.Ordinal)
        {
            ["zero"] = 0,
            ["jeden"] = 1,
            ["jedna"] = 1,
            ["jedno"] = 1,
            ["dwa"] = 2,
            ["dwie"] = 2,
            ["trzy"] = 3,
            ["cztery"] = 4,
            ["pięć"] = 5,
            ["piec"] = 5,
            ["sześć"] = 6,
            ["szesc"] = 6,
            ["siedem"] = 7,
            ["osiem"] = 8,
            ["dziewięć"] = 9,
            ["dziewiec"] = 9,
            ["dziesięć"] = 10,
            ["dziesiec"] = 10,
            ["jedenaście"] = 11,
            ["jedenascie"] = 11,
            ["dwanaście"] = 12,
            ["dwanascie"] = 12,
            ["trzynaście"] = 13,
            ["trzynascie"] = 13,
            ["czternaście"] = 14,
            ["czternascie"] = 14,
            ["piętnaście"] = 15,
            ["pietnascie"] = 15,
            ["szesnaście"] = 16,
            ["szesnascie"] = 16,
            ["siedemnaście"] = 17,
            ["siedemnascie"] = 17,
            ["osiemnaście"] = 18,
            ["osiemnascie"] = 18,
            ["dziewiętnaście"] = 19,
            ["dziewietnascie"] = 19,
            ["dwadzieścia"] = 20,
            ["dwadziescia"] = 20,
            ["trzydzieści"] = 30,
            ["trzydziesci"] = 30,
            ["czterdzieści"] = 40,
            ["czterdziesci"] = 40,
            ["pięćdziesiąt"] = 50,
            ["piecdziesiat"] = 50,
            ["sześćdziesiąt"] = 60,
            ["szescdziesiat"] = 60,
            ["siedemdziesiąt"] = 70,
            ["siedemdziesiat"] = 70,
            ["osiemdziesiąt"] = 80,
            ["osiemdziesiat"] = 80,
            ["dziewięćdziesiąt"] = 90,
            ["dziewiecdziesiat"] = 90,
            ["sto"] = 100,
            ["dwieście"] = 200,
            ["dwiescie"] = 200,
            ["trzysta"] = 300,
            ["czterysta"] = 400,
            ["pięćset"] = 500,
            ["piecset"] = 500,
            ["sześćset"] = 600,
            ["szescset"] = 600,
            ["siedemset"] = 700,
            ["osiemset"] = 800,
            ["dziewięćset"] = 900,
            ["dziewiecset"] = 900,
            ["tysiąc"] = 1_000,
            ["tysiac"] = 1_000,
            ["tysiące"] = 1_000,
            ["tysiace"] = 1_000,
            ["tysięcy"] = 1_000,
            ["tysiecy"] = 1_000,
            ["milion"] = 1_000_000,
            ["miliony"] = 1_000_000,
            ["milionów"] = 1_000_000,
            ["milionow"] = 1_000_000,
            ["miliard"] = 1_000_000_000,
            ["miliardy"] = 1_000_000_000,
            ["miliardów"] = 1_000_000_000,
            ["miliardow"] = 1_000_000_000
        }.ToFrozenDictionary(StringComparer.Ordinal),
        NormalizationProfile = TokenMapNormalizationProfile.LowercaseRemovePeriods,
        NegativePrefixes = ["minus "]
    });

    public static IWordsToNumberConverter Russian { get; } = new TokenMapWordsToNumberConverter(new()
    {
        CardinalMap = new Dictionary<string, long>(StringComparer.Ordinal)
        {
            ["ноль"] = 0,
            ["один"] = 1,
            ["одна"] = 1,
            ["одно"] = 1,
            ["два"] = 2,
            ["две"] = 2,
            ["три"] = 3,
            ["четыре"] = 4,
            ["пять"] = 5,
            ["шесть"] = 6,
            ["семь"] = 7,
            ["восемь"] = 8,
            ["девять"] = 9,
            ["десять"] = 10,
            ["одиннадцать"] = 11,
            ["двенадцать"] = 12,
            ["тринадцать"] = 13,
            ["четырнадцать"] = 14,
            ["пятнадцать"] = 15,
            ["шестнадцать"] = 16,
            ["семнадцать"] = 17,
            ["восемнадцать"] = 18,
            ["девятнадцать"] = 19,
            ["двадцать"] = 20,
            ["тридцать"] = 30,
            ["сорок"] = 40,
            ["пятьдесят"] = 50,
            ["шестьдесят"] = 60,
            ["семьдесят"] = 70,
            ["восемьдесят"] = 80,
            ["девяносто"] = 90,
            ["сто"] = 100,
            ["двести"] = 200,
            ["триста"] = 300,
            ["четыреста"] = 400,
            ["пятьсот"] = 500,
            ["шестьсот"] = 600,
            ["семьсот"] = 700,
            ["восемьсот"] = 800,
            ["девятьсот"] = 900,
            ["тысяча"] = 1_000,
            ["тысячи"] = 1_000,
            ["тысяч"] = 1_000,
            ["миллион"] = 1_000_000,
            ["миллиона"] = 1_000_000,
            ["миллионов"] = 1_000_000,
            ["миллиард"] = 1_000_000_000,
            ["миллиарда"] = 1_000_000_000,
            ["миллиардов"] = 1_000_000_000
        }.ToFrozenDictionary(StringComparer.Ordinal),
        OrdinalMap = BuildRussianOrdinalMap(),
        NormalizationProfile = TokenMapNormalizationProfile.LowercaseRemovePeriods,
        NegativePrefixes = ["минус "]
    });

    public static IWordsToNumberConverter SerbianCyrillic { get; } = new TokenMapWordsToNumberConverter(new()
    {
        CardinalMap = new Dictionary<string, long>(StringComparer.Ordinal)
        {
            ["нула"] = 0,
            ["један"] = 1,
            ["једна"] = 1,
            ["једно"] = 1,
            ["два"] = 2,
            ["две"] = 2,
            ["три"] = 3,
            ["четири"] = 4,
            ["пет"] = 5,
            ["шест"] = 6,
            ["седам"] = 7,
            ["осам"] = 8,
            ["девет"] = 9,
            ["десет"] = 10,
            ["једанаест"] = 11,
            ["дванаест"] = 12,
            ["тринаест"] = 13,
            ["четрнаест"] = 14,
            ["петнаест"] = 15,
            ["шеснаест"] = 16,
            ["седамнаест"] = 17,
            ["осамнаест"] = 18,
            ["деветнаест"] = 19,
            ["двадесет"] = 20,
            ["тридесет"] = 30,
            ["четрдесет"] = 40,
            ["педесет"] = 50,
            ["шестдесет"] = 60,
            ["седамдесет"] = 70,
            ["осамдесет"] = 80,
            ["деветдесет"] = 90,
            ["сто"] = 100,
            ["двесто"] = 200,
            ["тристо"] = 300,
            ["четиристо"] = 400,
            ["петсто"] = 500,
            ["шестсто"] = 600,
            ["седамсто"] = 700,
            ["осамсто"] = 800,
            ["деветсто"] = 900,
            ["хиљаду"] = 1_000,
            ["хиљада"] = 1_000,
            ["милион"] = 1_000_000,
            ["милиона"] = 1_000_000,
            ["милијарда"] = 1_000_000_000,
            ["милијарде"] = 1_000_000_000
        }.ToFrozenDictionary(StringComparer.Ordinal),
        NormalizationProfile = TokenMapNormalizationProfile.LowercaseRemovePeriods,
        NegativePrefixes = ["минус "]
    });

    public static IWordsToNumberConverter SerbianLatin { get; } = new TokenMapWordsToNumberConverter(new()
    {
        CardinalMap = new Dictionary<string, long>(StringComparer.Ordinal)
        {
            ["nula"] = 0,
            ["jedan"] = 1,
            ["jedna"] = 1,
            ["jedno"] = 1,
            ["dva"] = 2,
            ["dve"] = 2,
            ["tri"] = 3,
            ["četiri"] = 4,
            ["cetiri"] = 4,
            ["pet"] = 5,
            ["šest"] = 6,
            ["sest"] = 6,
            ["sedam"] = 7,
            ["osam"] = 8,
            ["devet"] = 9,
            ["deset"] = 10,
            ["jedanaest"] = 11,
            ["dvanaest"] = 12,
            ["trinaest"] = 13,
            ["četrnaest"] = 14,
            ["cetrnaest"] = 14,
            ["petnaest"] = 15,
            ["šesnaest"] = 16,
            ["sesnaest"] = 16,
            ["sedamnaest"] = 17,
            ["osamnaest"] = 18,
            ["devetnaest"] = 19,
            ["dvadeset"] = 20,
            ["trideset"] = 30,
            ["četrdeset"] = 40,
            ["cetrdeset"] = 40,
            ["pedeset"] = 50,
            ["šestdeset"] = 60,
            ["sestdeset"] = 60,
            ["sedamdeset"] = 70,
            ["osamdeset"] = 80,
            ["devedeset"] = 90,
            ["sto"] = 100,
            ["dvesto"] = 200,
            ["tristo"] = 300,
            ["četiristo"] = 400,
            ["cetiristo"] = 400,
            ["petsto"] = 500,
            ["šeststo"] = 600,
            ["seststo"] = 600,
            ["sedamsto"] = 700,
            ["osamsto"] = 800,
            ["devetsto"] = 900,
            ["hiljadu"] = 1_000,
            ["hiljada"] = 1_000,
            ["milion"] = 1_000_000,
            ["miliona"] = 1_000_000,
            ["milijarda"] = 1_000_000_000,
            ["milijarde"] = 1_000_000_000
        }.ToFrozenDictionary(StringComparer.Ordinal),
        NormalizationProfile = TokenMapNormalizationProfile.LowercaseRemovePeriods,
        NegativePrefixes = ["minus "]
    });

    public static IWordsToNumberConverter Turkish { get; } = new TokenMapWordsToNumberConverter(new()
    {
        CardinalMap = new Dictionary<string, long>(StringComparer.Ordinal)
        {
            ["sıfır"] = 0,
            ["bir"] = 1,
            ["iki"] = 2,
            ["üç"] = 3,
            ["dört"] = 4,
            ["beş"] = 5,
            ["altı"] = 6,
            ["yedi"] = 7,
            ["sekiz"] = 8,
            ["dokuz"] = 9,
            ["on"] = 10,
            ["yirmi"] = 20,
            ["otuz"] = 30,
            ["kırk"] = 40,
            ["elli"] = 50,
            ["altmış"] = 60,
            ["yetmiş"] = 70,
            ["seksen"] = 80,
            ["doksan"] = 90,
            ["yüz"] = 100,
            ["bin"] = 1000,
            ["milyon"] = 1_000_000,
            ["milyar"] = 1_000_000_000
        }.ToFrozenDictionary(StringComparer.Ordinal),
        OrdinalMap = BuildTurkishOrdinalMap(),
        NormalizationProfile = TokenMapNormalizationProfile.CollapseWhitespace,
        NegativePrefixes = ["eksi "],
        UseHundredMultiplier = true
    });

    public static IWordsToNumberConverter Ukrainian { get; } = new TokenMapWordsToNumberConverter(new()
    {
        CardinalMap = new Dictionary<string, long>(StringComparer.Ordinal)
        {
            ["нуль"] = 0,
            ["один"] = 1,
            ["одна"] = 1,
            ["одне"] = 1,
            ["два"] = 2,
            ["дві"] = 2,
            ["три"] = 3,
            ["чотири"] = 4,
            ["п'ять"] = 5,
            ["пять"] = 5,
            ["шість"] = 6,
            ["сім"] = 7,
            ["вісім"] = 8,
            ["дев'ять"] = 9,
            ["девять"] = 9,
            ["десять"] = 10,
            ["одинадцять"] = 11,
            ["дванадцять"] = 12,
            ["тринадцять"] = 13,
            ["чотирнадцять"] = 14,
            ["п'ятнадцять"] = 15,
            ["пятнадцять"] = 15,
            ["шістнадцять"] = 16,
            ["сімнадцять"] = 17,
            ["вісімнадцять"] = 18,
            ["дев'ятнадцять"] = 19,
            ["девятнадцять"] = 19,
            ["двадцять"] = 20,
            ["тридцять"] = 30,
            ["сорок"] = 40,
            ["п'ятдесят"] = 50,
            ["пятдесят"] = 50,
            ["шістдесят"] = 60,
            ["сімдесят"] = 70,
            ["вісімдесят"] = 80,
            ["дев'яносто"] = 90,
            ["девяносто"] = 90,
            ["сто"] = 100,
            ["двісті"] = 200,
            ["триста"] = 300,
            ["чотириста"] = 400,
            ["п'ятсот"] = 500,
            ["пятсот"] = 500,
            ["шістсот"] = 600,
            ["сімсот"] = 700,
            ["вісімсот"] = 800,
            ["дев'ятсот"] = 900,
            ["девятсот"] = 900,
            ["тисяча"] = 1_000,
            ["тисячі"] = 1_000,
            ["тисяч"] = 1_000,
            ["мільйон"] = 1_000_000,
            ["мільйона"] = 1_000_000,
            ["мільйонів"] = 1_000_000,
            ["мільярд"] = 1_000_000_000,
            ["мільярда"] = 1_000_000_000,
            ["мільярдів"] = 1_000_000_000
        }.ToFrozenDictionary(StringComparer.Ordinal),
        OrdinalMap = BuildUkrainianOrdinalMap(),
        NormalizationProfile = TokenMapNormalizationProfile.LowercaseRemovePeriods,
        NegativePrefixes = ["мінус ", "минус "]
    });

    public static IWordsToNumberConverter UzbekCyrl { get; } = new TokenMapWordsToNumberConverter(new()
    {
        CardinalMap = new Dictionary<string, long>(StringComparer.Ordinal)
        {
            ["нол"] = 0,
            ["бир"] = 1,
            ["иккинчи"] = 2,
            ["икки"] = 2,
            ["уч"] = 3,
            ["тўрт"] = 4,
            ["беш"] = 5,
            ["олти"] = 6,
            ["етти"] = 7,
            ["саккиз"] = 8,
            ["тўққиз"] = 9,
            ["ўн"] = 10,
            ["йигирма"] = 20,
            ["ўттиз"] = 30,
            ["қирқ"] = 40,
            ["эллик"] = 50,
            ["олтмиш"] = 60,
            ["етмиш"] = 70,
            ["саксон"] = 80,
            ["тўқсон"] = 90,
            ["юз"] = 100,
            ["минг"] = 1000,
            ["миллион"] = 1_000_000,
            ["миллиард"] = 1_000_000_000
        }.ToFrozenDictionary(StringComparer.Ordinal),
        NormalizationProfile = TokenMapNormalizationProfile.CollapseWhitespace,
        NegativePrefixes = ["минус "],
        TokenSuffixesToStrip = ["инчи", "нчи"],
        UseHundredMultiplier = true
    });

    public static IWordsToNumberConverter UzbekLatn { get; } = new TokenMapWordsToNumberConverter(new()
    {
        CardinalMap = new Dictionary<string, long>(StringComparer.Ordinal)
        {
            ["nol"] = 0,
            ["bir"] = 1,
            ["ikkinchi"] = 2,
            ["ikki"] = 2,
            ["uch"] = 3,
            ["to`rt"] = 4,
            ["besh"] = 5,
            ["olti"] = 6,
            ["yetti"] = 7,
            ["sakkiz"] = 8,
            ["to`qqiz"] = 9,
            ["o`n"] = 10,
            ["yigirma"] = 20,
            ["o`ttiz"] = 30,
            ["qirq"] = 40,
            ["ellik"] = 50,
            ["oltmish"] = 60,
            ["yetmish"] = 70,
            ["sakson"] = 80,
            ["to`qson"] = 90,
            ["yuz"] = 100,
            ["ming"] = 1000,
            ["million"] = 1_000_000,
            ["milliard"] = 1_000_000_000
        }.ToFrozenDictionary(StringComparer.Ordinal),
        NormalizationProfile = TokenMapNormalizationProfile.CollapseWhitespace,
        NegativePrefixes = ["minus "],
        TokenSuffixesToStrip = ["inchi", "nchi"],
        UseHundredMultiplier = true
    });

    public static IWordsToNumberConverter Azerbaijani { get; } = new TokenMapWordsToNumberConverter(new()
    {
        CardinalMap = new Dictionary<string, long>(StringComparer.Ordinal)
        {
            ["sıfır"] = 0,
            ["bir"] = 1,
            ["iki"] = 2,
            ["üç"] = 3,
            ["dörd"] = 4,
            ["beş"] = 5,
            ["altı"] = 6,
            ["yeddi"] = 7,
            ["səkkiz"] = 8,
            ["doqquz"] = 9,
            ["on"] = 10,
            ["iyirmi"] = 20,
            ["otuz"] = 30,
            ["qırx"] = 40,
            ["əlli"] = 50,
            ["altmış"] = 60,
            ["yetmiş"] = 70,
            ["səksən"] = 80,
            ["doxsan"] = 90,
            ["yüz"] = 100,
            ["min"] = 1000,
            ["milyon"] = 1_000_000
        }.ToFrozenDictionary(StringComparer.Ordinal),
        OrdinalMap = BuildAzerbaijaniOrdinalMap(),
        NormalizationProfile = TokenMapNormalizationProfile.CollapseWhitespace,
        NegativePrefixes = ["mənfi "],
        UseHundredMultiplier = true
    });

    static FrozenDictionary<string, int> BuildAzerbaijaniOrdinalMap()
    {
        var converter = new AzerbaijaniNumberToWordsConverter();
        var ordinals = new Dictionary<string, int>(StringComparer.Ordinal);

        for (var number = 1; number <= 200; number++)
        {
            ordinals[converter.ConvertToOrdinal(number)] = number;
        }

        return ordinals.ToFrozenDictionary(StringComparer.Ordinal);
    }

    static FrozenDictionary<string, int> BuildCatalanOrdinalMap()
    {
        var converter = new CatalanNumberToWordsConverter();
        var ordinals = new Dictionary<string, int>(StringComparer.Ordinal);

        for (var number = 1; number <= 200; number++)
        {
            ordinals[NormalizeLowercase(converter.ConvertToOrdinal(number, GrammaticalGender.Masculine))] = number;
            ordinals[NormalizeLowercase(converter.ConvertToOrdinal(number, GrammaticalGender.Feminine))] = number;
        }

        return ordinals.ToFrozenDictionary(StringComparer.Ordinal);
    }

    static FrozenDictionary<string, int> BuildRussianOrdinalMap()
    {
        var converter = new RussianNumberToWordsConverter();
        var ordinals = new Dictionary<string, int>(StringComparer.Ordinal);

        for (var number = 1; number <= 200; number++)
        {
            ordinals[NormalizeLowercase(converter.ConvertToOrdinal(number))] = number;
            ordinals[NormalizeLowercase(converter.ConvertToOrdinal(number, GrammaticalGender.Feminine))] = number;
            ordinals[NormalizeLowercase(converter.ConvertToOrdinal(number, GrammaticalGender.Neuter))] = number;
        }

        return ordinals.ToFrozenDictionary(StringComparer.Ordinal);
    }

    static FrozenDictionary<string, int> BuildTurkishOrdinalMap()
    {
        var converter = new TurkishNumberToWordConverter();
        var ordinals = new Dictionary<string, int>(StringComparer.Ordinal);

        for (var number = 1; number <= 200; number++)
        {
            ordinals[TokenMapWordsToNumberNormalizer.Normalize(converter.ConvertToOrdinal(number), TokenMapNormalizationProfile.CollapseWhitespace)] = number;
        }

        return ordinals.ToFrozenDictionary(StringComparer.Ordinal);
    }

    static FrozenDictionary<string, int> BuildUkrainianOrdinalMap()
    {
        var converter = new UkrainianNumberToWordsConverter();
        var ordinals = new Dictionary<string, int>(StringComparer.Ordinal);

        for (var number = 1; number <= 200; number++)
        {
            ordinals[NormalizeLowercase(converter.ConvertToOrdinal(number))] = number;
            ordinals[NormalizeLowercase(converter.ConvertToOrdinal(number, GrammaticalGender.Feminine))] = number;
            ordinals[NormalizeLowercase(converter.ConvertToOrdinal(number, GrammaticalGender.Neuter))] = number;
        }

        return ordinals.ToFrozenDictionary(StringComparer.Ordinal);
    }

    static string NormalizeLowercase(string words) =>
        TokenMapWordsToNumberNormalizer.Normalize(words, TokenMapNormalizationProfile.LowercaseRemovePeriods);
}
