namespace sr;

[UseCulture("sr")]
public class NumberToWordsTest
{
    [Theory]
    [InlineData(0, "нула")]
    [InlineData(1, "један")]
    [InlineData(2, "два")]
    [InlineData(3, "три")]
    [InlineData(4, "четири")]
    [InlineData(5, "пет")]
    [InlineData(6, "шест")]
    [InlineData(7, "седам")]
    [InlineData(8, "осам")]
    [InlineData(9, "девет")]
    [InlineData(10, "десет")]
    [InlineData(11, "једанаест")]
    [InlineData(20, "двадесет")]
    [InlineData(30, "тридесет")]
    [InlineData(40, "четрдесет")]
    [InlineData(50, "петдесет")]
    [InlineData(60, "шестдесет")]
    [InlineData(70, "седамдесет")]
    [InlineData(80, "осамдесет")]
    [InlineData(90, "деветдесет")]
    [InlineData(100, "сто")]
    [InlineData(200, "двесто")]
    [InlineData(300, "тристо")]
    [InlineData(400, "четиристо")]
    [InlineData(1000, "хиљаду")]
    [InlineData(1001, "хиљаду један")]
    [InlineData(10000, "десет хиљада")]
    [InlineData(21000, "двадесет једна хиљада")]
    [InlineData(100000, "сто хиљада")]
    [InlineData(1000000, "милион")]
    [InlineData(10000000, "десет милиона")]
    [InlineData(100000000, "сто милиона")]
    [InlineData(1000000000, "милијарда")]
    [InlineData(2000000000, "две милијарде")]
    [InlineData(1000000000000, "билион")]
    [InlineData(2000000000000000, "две билијарде")]
    [InlineData(15, "петнаест")]
    [InlineData(43, "четрдесет три")]
    [InlineData(81, "осамдесет један")]
    [InlineData(213, "двесто тринаест")]
    [InlineData(547, "петсто четрдесет седам")]
    public void ToWordsSr(long number, string expected) =>
        Assert.Equal(expected, number.ToWords());
}
