//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Humanizer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Humanizer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days ago.
        /// </summary>
        public static string DateHumanize__days_ago {
            get {
                return ResourceManager.GetString("DateHumanize__days_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours ago.
        /// </summary>
        public static string DateHumanize__hours_ago {
            get {
                return ResourceManager.GetString("DateHumanize__hours_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes ago.
        /// </summary>
        public static string DateHumanize__minutes_ago {
            get {
                return ResourceManager.GetString("DateHumanize__minutes_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} months ago.
        /// </summary>
        public static string DateHumanize__months_ago {
            get {
                return ResourceManager.GetString("DateHumanize__months_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} seconds ago.
        /// </summary>
        public static string DateHumanize__seconds_ago {
            get {
                return ResourceManager.GetString("DateHumanize__seconds_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} years ago.
        /// </summary>
        public static string DateHumanize__years_ago {
            get {
                return ResourceManager.GetString("DateHumanize__years_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a minute ago.
        /// </summary>
        public static string DateHumanize_a_minute_ago {
            get {
                return ResourceManager.GetString("DateHumanize_a_minute_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to an hour ago.
        /// </summary>
        public static string DateHumanize_an_hour_ago {
            get {
                return ResourceManager.GetString("DateHumanize_an_hour_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not yet.
        /// </summary>
        public static string DateHumanize_not_yet {
            get {
                return ResourceManager.GetString("DateHumanize_not_yet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one month ago.
        /// </summary>
        public static string DateHumanize_one_month_ago {
            get {
                return ResourceManager.GetString("DateHumanize_one_month_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one second ago.
        /// </summary>
        public static string DateHumanize_one_second_ago {
            get {
                return ResourceManager.GetString("DateHumanize_one_second_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one year ago.
        /// </summary>
        public static string DateHumanize_one_year_ago {
            get {
                return ResourceManager.GetString("DateHumanize_one_year_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yesterday.
        /// </summary>
        public static string DateHumanize_yesterday {
            get {
                return ResourceManager.GetString("DateHumanize_yesterday", resourceCulture);
            }
        }
    }
}
