//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Humanizer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_ua {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_ua() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Humanizer.Properties.Resources.ua", typeof(Resources_ua).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} днів тому.
        /// </summary>
        internal static string DateHumanize_MultipleDaysAgo {
            get {
                return ResourceManager.GetString("DateHumanize_MultipleDaysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} дні тому.
        /// </summary>
        internal static string DateHumanize_MultipleDaysAgo_Paucal {
            get {
                return ResourceManager.GetString("DateHumanize_MultipleDaysAgo_Paucal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} день тому.
        /// </summary>
        internal static string DateHumanize_MultipleDaysAgo_Singular {
            get {
                return ResourceManager.GetString("DateHumanize_MultipleDaysAgo_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to через {0} днів.
        /// </summary>
        internal static string DateHumanize_MultipleDaysFromNow {
            get {
                return ResourceManager.GetString("DateHumanize_MultipleDaysFromNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to через {0} дні.
        /// </summary>
        internal static string DateHumanize_MultipleDaysFromNow_Paucal {
            get {
                return ResourceManager.GetString("DateHumanize_MultipleDaysFromNow_Paucal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to через {0} день.
        /// </summary>
        internal static string DateHumanize_MultipleDaysFromNow_Singular {
            get {
                return ResourceManager.GetString("DateHumanize_MultipleDaysFromNow_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} годин тому.
        /// </summary>
        internal static string DateHumanize_MultipleHoursAgo {
            get {
                return ResourceManager.GetString("DateHumanize_MultipleHoursAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} години тому.
        /// </summary>
        internal static string DateHumanize_MultipleHoursAgo_Paucal {
            get {
                return ResourceManager.GetString("DateHumanize_MultipleHoursAgo_Paucal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} годину тому.
        /// </summary>
        internal static string DateHumanize_MultipleHoursAgo_Singular {
            get {
                return ResourceManager.GetString("DateHumanize_MultipleHoursAgo_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to через {0} годин.
        /// </summary>
        internal static string DateHumanize_MultipleHoursFromNow {
            get {
                return ResourceManager.GetString("DateHumanize_MultipleHoursFromNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to через {0} години.
        /// </summary>
        internal static string DateHumanize_MultipleHoursFromNow_Paucal {
            get {
                return ResourceManager.GetString("DateHumanize_MultipleHoursFromNow_Paucal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to через {0} годину.
        /// </summary>
        internal static string DateHumanize_MultipleHoursFromNow_Singular {
            get {
                return ResourceManager.GetString("DateHumanize_MultipleHoursFromNow_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} хвилин тому.
        /// </summary>
        internal static string DateHumanize_MultipleMinutesAgo {
            get {
                return ResourceManager.GetString("DateHumanize_MultipleMinutesAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} хвилини тому.
        /// </summary>
        internal static string DateHumanize_MultipleMinutesAgo_Paucal {
            get {
                return ResourceManager.GetString("DateHumanize_MultipleMinutesAgo_Paucal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} хвилини тому.
        /// </summary>
        internal static string DateHumanize_MultipleMinutesAgo_Singular {
            get {
                return ResourceManager.GetString("DateHumanize_MultipleMinutesAgo_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to через {0} хвилин.
        /// </summary>
        internal static string DateHumanize_MultipleMinutesFromNow {
            get {
                return ResourceManager.GetString("DateHumanize_MultipleMinutesFromNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to через {0} хвилини.
        /// </summary>
        internal static string DateHumanize_MultipleMinutesFromNow_Paucal {
            get {
                return ResourceManager.GetString("DateHumanize_MultipleMinutesFromNow_Paucal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to через {0} хвилину.
        /// </summary>
        internal static string DateHumanize_MultipleMinutesFromNow_Singular {
            get {
                return ResourceManager.GetString("DateHumanize_MultipleMinutesFromNow_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} місяців тому.
        /// </summary>
        internal static string DateHumanize_MultipleMonthsAgo {
            get {
                return ResourceManager.GetString("DateHumanize_MultipleMonthsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} місяці тому.
        /// </summary>
        internal static string DateHumanize_MultipleMonthsAgo_Paucal {
            get {
                return ResourceManager.GetString("DateHumanize_MultipleMonthsAgo_Paucal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} місяць тому.
        /// </summary>
        internal static string DateHumanize_MultipleMonthsAgo_Singular {
            get {
                return ResourceManager.GetString("DateHumanize_MultipleMonthsAgo_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to через {0} місяців.
        /// </summary>
        internal static string DateHumanize_MultipleMonthsFromNow {
            get {
                return ResourceManager.GetString("DateHumanize_MultipleMonthsFromNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to через {0} місяці.
        /// </summary>
        internal static string DateHumanize_MultipleMonthsFromNow_Paucal {
            get {
                return ResourceManager.GetString("DateHumanize_MultipleMonthsFromNow_Paucal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to через {0} місяць.
        /// </summary>
        internal static string DateHumanize_MultipleMonthsFromNow_Singular {
            get {
                return ResourceManager.GetString("DateHumanize_MultipleMonthsFromNow_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} секунд тому.
        /// </summary>
        internal static string DateHumanize_MultipleSecondsAgo {
            get {
                return ResourceManager.GetString("DateHumanize_MultipleSecondsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} секунди тому.
        /// </summary>
        internal static string DateHumanize_MultipleSecondsAgo_Paucal {
            get {
                return ResourceManager.GetString("DateHumanize_MultipleSecondsAgo_Paucal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} секунду тому.
        /// </summary>
        internal static string DateHumanize_MultipleSecondsAgo_Singular {
            get {
                return ResourceManager.GetString("DateHumanize_MultipleSecondsAgo_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to через {0} секунд.
        /// </summary>
        internal static string DateHumanize_MultipleSecondsFromNow {
            get {
                return ResourceManager.GetString("DateHumanize_MultipleSecondsFromNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to через {0} секунди.
        /// </summary>
        internal static string DateHumanize_MultipleSecondsFromNow_Paucal {
            get {
                return ResourceManager.GetString("DateHumanize_MultipleSecondsFromNow_Paucal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to через {0} секунду.
        /// </summary>
        internal static string DateHumanize_MultipleSecondsFromNow_Singular {
            get {
                return ResourceManager.GetString("DateHumanize_MultipleSecondsFromNow_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} років тому.
        /// </summary>
        internal static string DateHumanize_MultipleYearsAgo {
            get {
                return ResourceManager.GetString("DateHumanize_MultipleYearsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} роки тому.
        /// </summary>
        internal static string DateHumanize_MultipleYearsAgo_Paucal {
            get {
                return ResourceManager.GetString("DateHumanize_MultipleYearsAgo_Paucal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} рік тому.
        /// </summary>
        internal static string DateHumanize_MultipleYearsAgo_Singular {
            get {
                return ResourceManager.GetString("DateHumanize_MultipleYearsAgo_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to через {0} років.
        /// </summary>
        internal static string DateHumanize_MultipleYearsFromNow {
            get {
                return ResourceManager.GetString("DateHumanize_MultipleYearsFromNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to через {0} роки.
        /// </summary>
        internal static string DateHumanize_MultipleYearsFromNow_Paucal {
            get {
                return ResourceManager.GetString("DateHumanize_MultipleYearsFromNow_Paucal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to через {0} рік.
        /// </summary>
        internal static string DateHumanize_MultipleYearsFromNow_Singular {
            get {
                return ResourceManager.GetString("DateHumanize_MultipleYearsFromNow_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to зараз.
        /// </summary>
        internal static string DateHumanize_Now {
            get {
                return ResourceManager.GetString("DateHumanize_Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to вчора.
        /// </summary>
        internal static string DateHumanize_SingleDayAgo {
            get {
                return ResourceManager.GetString("DateHumanize_SingleDayAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to завтра.
        /// </summary>
        internal static string DateHumanize_SingleDayFromNow {
            get {
                return ResourceManager.GetString("DateHumanize_SingleDayFromNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to годину тому.
        /// </summary>
        internal static string DateHumanize_SingleHourAgo {
            get {
                return ResourceManager.GetString("DateHumanize_SingleHourAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to через годину.
        /// </summary>
        internal static string DateHumanize_SingleHourFromNow {
            get {
                return ResourceManager.GetString("DateHumanize_SingleHourFromNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to хвилину тому.
        /// </summary>
        internal static string DateHumanize_SingleMinuteAgo {
            get {
                return ResourceManager.GetString("DateHumanize_SingleMinuteAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to через хвилину.
        /// </summary>
        internal static string DateHumanize_SingleMinuteFromNow {
            get {
                return ResourceManager.GetString("DateHumanize_SingleMinuteFromNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to місяць тому.
        /// </summary>
        internal static string DateHumanize_SingleMonthAgo {
            get {
                return ResourceManager.GetString("DateHumanize_SingleMonthAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to через місяць.
        /// </summary>
        internal static string DateHumanize_SingleMonthFromNow {
            get {
                return ResourceManager.GetString("DateHumanize_SingleMonthFromNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to секунду тому.
        /// </summary>
        internal static string DateHumanize_SingleSecondAgo {
            get {
                return ResourceManager.GetString("DateHumanize_SingleSecondAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to через секунду.
        /// </summary>
        internal static string DateHumanize_SingleSecondFromNow {
            get {
                return ResourceManager.GetString("DateHumanize_SingleSecondFromNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to рік тому.
        /// </summary>
        internal static string DateHumanize_SingleYearAgo {
            get {
                return ResourceManager.GetString("DateHumanize_SingleYearAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to через рік.
        /// </summary>
        internal static string DateHumanize_SingleYearFromNow {
            get {
                return ResourceManager.GetString("DateHumanize_SingleYearFromNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} днів.
        /// </summary>
        internal static string TimeSpanHumanize_MultipleDays {
            get {
                return ResourceManager.GetString("TimeSpanHumanize_MultipleDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} дні.
        /// </summary>
        internal static string TimeSpanHumanize_MultipleDays_Paucal {
            get {
                return ResourceManager.GetString("TimeSpanHumanize_MultipleDays_Paucal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} день.
        /// </summary>
        internal static string TimeSpanHumanize_MultipleDays_Singular {
            get {
                return ResourceManager.GetString("TimeSpanHumanize_MultipleDays_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} годин.
        /// </summary>
        internal static string TimeSpanHumanize_MultipleHours {
            get {
                return ResourceManager.GetString("TimeSpanHumanize_MultipleHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} години.
        /// </summary>
        internal static string TimeSpanHumanize_MultipleHours_Paucal {
            get {
                return ResourceManager.GetString("TimeSpanHumanize_MultipleHours_Paucal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} година.
        /// </summary>
        internal static string TimeSpanHumanize_MultipleHours_Singular {
            get {
                return ResourceManager.GetString("TimeSpanHumanize_MultipleHours_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} мілісекунд.
        /// </summary>
        internal static string TimeSpanHumanize_MultipleMilliseconds {
            get {
                return ResourceManager.GetString("TimeSpanHumanize_MultipleMilliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} мілісекунди.
        /// </summary>
        internal static string TimeSpanHumanize_MultipleMilliseconds_Paucal {
            get {
                return ResourceManager.GetString("TimeSpanHumanize_MultipleMilliseconds_Paucal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} мілісекунда.
        /// </summary>
        internal static string TimeSpanHumanize_MultipleMilliseconds_Singular {
            get {
                return ResourceManager.GetString("TimeSpanHumanize_MultipleMilliseconds_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} хвилин.
        /// </summary>
        internal static string TimeSpanHumanize_MultipleMinutes {
            get {
                return ResourceManager.GetString("TimeSpanHumanize_MultipleMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} хвилини.
        /// </summary>
        internal static string TimeSpanHumanize_MultipleMinutes_Paucal {
            get {
                return ResourceManager.GetString("TimeSpanHumanize_MultipleMinutes_Paucal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} хвилина.
        /// </summary>
        internal static string TimeSpanHumanize_MultipleMinutes_Singular {
            get {
                return ResourceManager.GetString("TimeSpanHumanize_MultipleMinutes_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} секунд.
        /// </summary>
        internal static string TimeSpanHumanize_MultipleSeconds {
            get {
                return ResourceManager.GetString("TimeSpanHumanize_MultipleSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} секунди.
        /// </summary>
        internal static string TimeSpanHumanize_MultipleSeconds_Paucal {
            get {
                return ResourceManager.GetString("TimeSpanHumanize_MultipleSeconds_Paucal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} секунда.
        /// </summary>
        internal static string TimeSpanHumanize_MultipleSeconds_Singular {
            get {
                return ResourceManager.GetString("TimeSpanHumanize_MultipleSeconds_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} тижнів.
        /// </summary>
        internal static string TimeSpanHumanize_MultipleWeeks {
            get {
                return ResourceManager.GetString("TimeSpanHumanize_MultipleWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} тижні.
        /// </summary>
        internal static string TimeSpanHumanize_MultipleWeeks_Paucal {
            get {
                return ResourceManager.GetString("TimeSpanHumanize_MultipleWeeks_Paucal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} тиждень.
        /// </summary>
        internal static string TimeSpanHumanize_MultipleWeeks_Singular {
            get {
                return ResourceManager.GetString("TimeSpanHumanize_MultipleWeeks_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to один день.
        /// </summary>
        internal static string TimeSpanHumanize_SingleDay {
            get {
                return ResourceManager.GetString("TimeSpanHumanize_SingleDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to одна година.
        /// </summary>
        internal static string TimeSpanHumanize_SingleHour {
            get {
                return ResourceManager.GetString("TimeSpanHumanize_SingleHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to одна мілісекудна.
        /// </summary>
        internal static string TimeSpanHumanize_SingleMillisecond {
            get {
                return ResourceManager.GetString("TimeSpanHumanize_SingleMillisecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to одна хвилина.
        /// </summary>
        internal static string TimeSpanHumanize_SingleMinute {
            get {
                return ResourceManager.GetString("TimeSpanHumanize_SingleMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to одна секунда.
        /// </summary>
        internal static string TimeSpanHumanize_SingleSecond {
            get {
                return ResourceManager.GetString("TimeSpanHumanize_SingleSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to один тиждень.
        /// </summary>
        internal static string TimeSpanHumanize_SingleWeek {
            get {
                return ResourceManager.GetString("TimeSpanHumanize_SingleWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to щойно.
        /// </summary>
        internal static string TimeSpanHumanize_Zero {
            get {
                return ResourceManager.GetString("TimeSpanHumanize_Zero", resourceCulture);
            }
        }
    }
}
