using Xunit;

namespace Humanizer.Tests.Localisation.es
{
    [UseCulture("es-ES")]
    public class NumberToWordsTests
    {

        [Theory]
        [InlineData(0, "cero")]
        [InlineData(1, "uno")]
        [InlineData(10, "diez")]
        [InlineData(11, "once")]
        [InlineData(122, "ciento veintidós")]
        [InlineData(3501, "tres mil quinientos uno")]
        [InlineData(100, "cien")]
        [InlineData(1000, "mil")]
        [InlineData(100000, "cien mil")]
        [InlineData(1000000, "un millón")]
        [InlineData(10000000, "diez millones")]
        [InlineData(100000000, "cien millones")]
        [InlineData(1000000000, "mil millones")]
        [InlineData(111, "ciento once")]
        [InlineData(1111, "mil ciento once")]
        [InlineData(111111, "ciento once mil ciento once")]
        [InlineData(1111111, "un millón ciento once mil ciento once")]
        [InlineData(11111111, "once millones ciento once mil ciento once")]
        [InlineData(111111111, "ciento once millones ciento once mil ciento once")]
        [InlineData(1001111111, "mil millones un millón ciento once mil ciento once")]
        [InlineData(1111111111, "mil millones ciento once millones ciento once mil ciento once")]
        [InlineData(123, "ciento veintitrés")]
        [InlineData(1234, "mil doscientos treinta y cuatro")]
        [InlineData(12345, "doce mil trescientos cuarenta y cinco")]
        [InlineData(123456, "ciento veintitrés mil cuatrocientos cincuenta y seis")]
        [InlineData(1234567, "un millón doscientos treinta y cuatro mil quinientos sesenta y siete")]
        [InlineData(12345678, "doce millones trescientos cuarenta y cinco mil seiscientos setenta y ocho")]
        [InlineData(123456789, "ciento veintitrés millones cuatrocientos cincuenta y seis mil setecientos ochenta y nueve")]
        [InlineData(1234567890, "mil millones doscientos treinta y cuatro millones quinientos sesenta y siete mil ochocientos noventa")]
        [InlineData(15, "quince")]
        [InlineData(16, "dieciséis")]
        [InlineData(20, "veinte")]
        [InlineData(22, "veintidós")]
        [InlineData(25, "veinticinco")]
        [InlineData(35, "treinta y cinco")]
        [InlineData(1999, "mil novecientos noventa y nueve")]
        [InlineData(2014, "dos mil catorce")]
        [InlineData(2048, "dos mil cuarenta y ocho")]
        public void ToWords(int number, string expected)
        {
            Assert.Equal(expected, number.ToWords());
        }

        // TODO: This data is suspect since null cannot go into GramaticalGender
        [Theory]
        // [InlineData(1, "primer", null)]
        [InlineData(1, "primero", GrammaticalGender.Masculine)]
        [InlineData(1, "primera", GrammaticalGender.Feminine)]
        [InlineData(2, "segundo", GrammaticalGender.Masculine)]
        [InlineData(2, "segunda", GrammaticalGender.Feminine)]
        [InlineData(2, "segundo", GrammaticalGender.Neuter)]
        // [InlineData(3, "tercer", null)]
        [InlineData(3, "tercero", GrammaticalGender.Masculine)]
        [InlineData(3, "tercera", GrammaticalGender.Feminine)]
        //  [InlineData(11, "once", null)]
        [InlineData(4, "cuarto", GrammaticalGender.Masculine)]
        [InlineData(4, "cuarta", GrammaticalGender.Feminine)]
        [InlineData(5, "quinto", GrammaticalGender.Masculine)]
        [InlineData(5, "quinta", GrammaticalGender.Feminine)]
        [InlineData(6, "sexto", GrammaticalGender.Masculine)]
        [InlineData(6, "sexta", GrammaticalGender.Feminine)]
        [InlineData(7, "séptimo", GrammaticalGender.Masculine)]
        [InlineData(7, "séptima", GrammaticalGender.Feminine)]
        [InlineData(8, "octavo", GrammaticalGender.Masculine)]
        [InlineData(8, "octava", GrammaticalGender.Feminine)]
        [InlineData(9, "noveno", GrammaticalGender.Masculine)]
        [InlineData(9, "novena", GrammaticalGender.Feminine)]
        [InlineData(10, "décimo", GrammaticalGender.Masculine)]
        [InlineData(10, "décima", GrammaticalGender.Feminine)]
        [InlineData(11, "décimo primero", GrammaticalGender.Masculine)]
        [InlineData(11, "décima primera", GrammaticalGender.Feminine)]
        [InlineData(20, "vigésimo", GrammaticalGender.Masculine)]
        [InlineData(20, "vigésima", GrammaticalGender.Feminine)]
        [InlineData(22, "vigésimo segundo", GrammaticalGender.Masculine)]
        [InlineData(22, "vigésima segunda", GrammaticalGender.Feminine)]
        [InlineData(30, "trigésimo", GrammaticalGender.Masculine)]
        [InlineData(30, "trigésima", GrammaticalGender.Feminine)]
        [InlineData(34, "trigésimo cuarto", GrammaticalGender.Masculine)]
        [InlineData(34, "trigésima cuarta", GrammaticalGender.Feminine)]
        [InlineData(40, "cuadragésimo", GrammaticalGender.Masculine)]
        [InlineData(40, "cuadragésima", GrammaticalGender.Feminine)]
        [InlineData(46, "cuadragésimo sexto", GrammaticalGender.Masculine)]
        [InlineData(46, "cuadragésima sexta", GrammaticalGender.Feminine)]
        [InlineData(50, "quincuagésimo", GrammaticalGender.Masculine)]
        [InlineData(50, "quincuagésima", GrammaticalGender.Feminine)]
        [InlineData(57, "quincuagésimo séptimo", GrammaticalGender.Masculine)]
        [InlineData(57, "quincuagésima séptima", GrammaticalGender.Feminine)]
        [InlineData(60, "sexagésimo", GrammaticalGender.Masculine)]
        [InlineData(60, "sexagésima", GrammaticalGender.Feminine)]
        [InlineData(69, "sexagésimo noveno", GrammaticalGender.Masculine)]
        [InlineData(69, "sexagésima novena", GrammaticalGender.Feminine)]
        [InlineData(70, "septuagésimo", GrammaticalGender.Masculine)]
        [InlineData(70, "septuagésima", GrammaticalGender.Feminine)]
        [InlineData(74, "septuagésimo cuarto", GrammaticalGender.Masculine)]
        [InlineData(74, "septuagésima cuarta", GrammaticalGender.Feminine)]
        [InlineData(80, "octogésimo", GrammaticalGender.Masculine)]
        [InlineData(80, "octogésima", GrammaticalGender.Feminine)]
        [InlineData(85, "octogésimo quinto", GrammaticalGender.Masculine)]
        [InlineData(85, "octogésima quinta", GrammaticalGender.Feminine)]
        [InlineData(90, "nonagésimo", GrammaticalGender.Masculine)]
        [InlineData(90, "nonagésima", GrammaticalGender.Feminine)]
        [InlineData(99, "nonagésimo noveno", GrammaticalGender.Masculine)]
        [InlineData(99, "nonagésima novena", GrammaticalGender.Feminine)]
        [InlineData(100, "centésimo", GrammaticalGender.Masculine)]
        [InlineData(100, "centésima", GrammaticalGender.Feminine)]
        [InlineData(101, "centésimo primero", GrammaticalGender.Masculine)]
        [InlineData(101, "centésima primera", GrammaticalGender.Feminine)]
        [InlineData(131, "centésimo trigésimo primero", GrammaticalGender.Masculine)]
        [InlineData(131, "centésima trigésima primera", GrammaticalGender.Feminine)]
        [InlineData(156, "centésimo quincuagésimo sexto", GrammaticalGender.Masculine)]
        [InlineData(156, "centésima quincuagésima sexta", GrammaticalGender.Feminine)]
        [InlineData(214, "ducentésimo décimo cuarto", GrammaticalGender.Masculine)]
        [InlineData(214, "ducentésima décima cuarta", GrammaticalGender.Feminine)]
        [InlineData(330, "tricentésimo trigésimo", GrammaticalGender.Masculine)]
        [InlineData(330, "tricentésima trigésima", GrammaticalGender.Feminine)]
        [InlineData(334, "tricentésimo trigésimo cuarto", GrammaticalGender.Masculine)]
        [InlineData(334, "tricentésima trigésima cuarta", GrammaticalGender.Feminine)]
        [InlineData(400, "cuadringentésimo", GrammaticalGender.Masculine)]
        [InlineData(400, "cuadringentésima", GrammaticalGender.Feminine)]
        [InlineData(407, "cuadringentésimo séptimo", GrammaticalGender.Masculine)]
        [InlineData(407, "cuadringentésima séptima", GrammaticalGender.Feminine)]
        [InlineData(476, "cuadringentésimo septuagésimo sexto", GrammaticalGender.Masculine)]
        [InlineData(476, "cuadringentésima septuagésima sexta", GrammaticalGender.Feminine)]
        [InlineData(500, "quingentésimo", GrammaticalGender.Masculine)]
        [InlineData(500, "quingentésima", GrammaticalGender.Feminine)]
        [InlineData(509, "quingentésimo noveno", GrammaticalGender.Masculine)]
        [InlineData(509, "quingentésima novena", GrammaticalGender.Feminine)]
        [InlineData(549, "quingentésimo cuadragésimo noveno", GrammaticalGender.Masculine)]
        [InlineData(549, "quingentésima cuadragésima novena", GrammaticalGender.Feminine)]
        [InlineData(600, "sexcentésimo", GrammaticalGender.Masculine)]
        [InlineData(600, "sexcentésima", GrammaticalGender.Feminine)]
        [InlineData(605, "sexcentésimo quinto", GrammaticalGender.Masculine)]
        [InlineData(605, "sexcentésima quinta", GrammaticalGender.Feminine)]
        [InlineData(670, "sexcentésimo septuagésimo", GrammaticalGender.Masculine)]
        [InlineData(670, "sexcentésima septuagésima", GrammaticalGender.Feminine)]
        [InlineData(692, "sexcentésimo nonagésimo segundo", GrammaticalGender.Masculine)]
        [InlineData(692, "sexcentésima nonagésima segunda", GrammaticalGender.Feminine)]
        [InlineData(700, "septingentésimo", GrammaticalGender.Masculine)]
        [InlineData(700, "septingentésima", GrammaticalGender.Feminine)]
        [InlineData(771, "septingentésimo septuagésimo primero", GrammaticalGender.Masculine)]
        [InlineData(771, "septingentésima septuagésima primera", GrammaticalGender.Feminine)]
        [InlineData(800, "octingentésimo", GrammaticalGender.Masculine)]
        [InlineData(800, "octingentésima", GrammaticalGender.Feminine)]
        [InlineData(849, "octingentésimo cuadragésimo noveno", GrammaticalGender.Masculine)]
        [InlineData(849, "octingentésima cuadragésima novena", GrammaticalGender.Feminine)]
        [InlineData(900, "noningentésimo", GrammaticalGender.Masculine)]
        [InlineData(900, "noningentésima", GrammaticalGender.Feminine)]
        [InlineData(921, "noningentésimo vigésimo primero", GrammaticalGender.Masculine)]
        [InlineData(921, "noningentésima vigésima primera", GrammaticalGender.Feminine)]
        [InlineData(1000, "milésimo", GrammaticalGender.Masculine)]
        [InlineData(1000, "milésima", GrammaticalGender.Feminine)]
        [InlineData(1006, "milésimo sexto", GrammaticalGender.Masculine)]
        [InlineData(1006, "milésima sexta", GrammaticalGender.Feminine)]
        [InlineData(1108, "milésimo centésimo octavo", GrammaticalGender.Masculine)]
        [InlineData(1108, "milésima centésima octava", GrammaticalGender.Feminine)]
        [InlineData(1323, "milésimo tricentésimo vigésimo tercero", GrammaticalGender.Masculine)]
        [InlineData(1323, "milésima tricentésima vigésima tercera", GrammaticalGender.Feminine)]
        [InlineData(2000, "dosmilésimo", GrammaticalGender.Masculine)]
        [InlineData(2000, "dosmilésima", GrammaticalGender.Feminine)]
        [InlineData(2164, "dosmilésimo centésimo sexagésimo cuarto", GrammaticalGender.Masculine)]
        [InlineData(2164, "dosmilésima centésima sexagésima cuarta", GrammaticalGender.Feminine)]
        [InlineData(2915, "dosmilésimo noningentésimo décimo quinto", GrammaticalGender.Masculine)]
        [InlineData(2915, "dosmilésima noningentésima décima quinta", GrammaticalGender.Feminine)]
        [InlineData(3000, "tresmilésimo", GrammaticalGender.Masculine)]
        [InlineData(3000, "tresmilésima", GrammaticalGender.Feminine)]
        [InlineData(3456, "tresmilésimo cuadringentésimo quincuagésimo sexto", GrammaticalGender.Masculine)]
        [InlineData(3456, "tresmilésima cuadringentésima quincuagésima sexta", GrammaticalGender.Feminine)]
        [InlineData(4000, "cuatromilésimo", GrammaticalGender.Masculine)]
        [InlineData(4000, "cuatromilésima", GrammaticalGender.Feminine)]
        [InlineData(4354, "cuatromilésimo tricentésimo quincuagésimo cuarto", GrammaticalGender.Masculine)]
        [InlineData(4354, "cuatromilésima tricentésima quincuagésima cuarta", GrammaticalGender.Feminine)]
        [InlineData(5000, "cincomilésimo", GrammaticalGender.Masculine)]
        [InlineData(5000, "cincomilésima", GrammaticalGender.Feminine)]
        [InlineData(5695, "cincomilésimo sexcentésimo nonagésimo quinto", GrammaticalGender.Masculine)]
        [InlineData(5695, "cincomilésima sexcentésima nonagésima quinta", GrammaticalGender.Feminine)]
        [InlineData(6000, "seismilésimo", GrammaticalGender.Masculine)]
        [InlineData(6000, "seismilésima", GrammaticalGender.Feminine)]
        [InlineData(6642, "seismilésimo sexcentésimo cuadragésimo segundo", GrammaticalGender.Masculine)]
        [InlineData(6642, "seismilésima sexcentésima cuadragésima segunda", GrammaticalGender.Feminine)]
        [InlineData(7000, "sietemilésimo", GrammaticalGender.Masculine)]
        [InlineData(7000, "sietemilésima", GrammaticalGender.Feminine)]
        [InlineData(7676, "sietemilésimo sexcentésimo septuagésimo sexto", GrammaticalGender.Masculine)]
        [InlineData(7676, "sietemilésima sexcentésima septuagésima sexta", GrammaticalGender.Feminine)]
        [InlineData(8000, "ochomilésimo", GrammaticalGender.Masculine)]
        [InlineData(8000, "ochomilésima", GrammaticalGender.Feminine)]
        [InlineData(8431, "ochomilésimo cuadringentésimo trigésimo primero", GrammaticalGender.Masculine)]
        [InlineData(8431, "ochomilésima cuadringentésima trigésima primera", GrammaticalGender.Feminine)]
        [InlineData(9000, "nuevemilésimo", GrammaticalGender.Masculine)]
        [InlineData(9000, "nuevemilésima", GrammaticalGender.Feminine)]
        [InlineData(9620, "nuevemilésimo sexcentésimo vigésimo", GrammaticalGender.Masculine)]
        [InlineData(9620, "nuevemilésima sexcentésima vigésima", GrammaticalGender.Feminine)]
        [InlineData(9999, "nuevemilésimo noningentésimo nonagésimo noveno", GrammaticalGender.Masculine)]
        [InlineData(9999, "nuevemilésima noningentésima nonagésima novena", GrammaticalGender.Feminine)]
        public void ToOrdinalWords(int number, string words, GrammaticalGender gender)
        {
            Assert.Equal(words, number.ToOrdinalWords(gender));
        }
    }
}
