global using System;
global using System.Collections;
global using System.Collections.Generic;
global using System.Collections.Frozen;
global using System.Globalization;
global using System.Linq;
global using System.Reflection;
global using System.Text;
global using System.Text.RegularExpressions;
global using System.Threading;
global using System.Diagnostics.CodeAnalysis;
global using CharSpan = System.ReadOnlySpan<char>;