using Xunit;

namespace Humanizer.Tests.Localisation.lt
{
    [UseCulture("lt-LT")]
    public class NumberToWordsTests
    {
        [Theory]
        [InlineData(0, "nulis")]
        [InlineData(21, "dvidešimt vienas")]
        [InlineData(22, "dvidešimt du")]
        [InlineData(26, "dvidešimt šeši")]
        [InlineData(30, "trisdešimt")]
        [InlineData(31, "trisdešimt vienas")]
        [InlineData(33, "trisdešimt trys")]
        [InlineData(37, "trisdešimt septyni")]
        [InlineData(40, "keturiasdešimt")]
        [InlineData(41, "keturiasdešimt vienas")]
        [InlineData(44, "keturiasdešimt keturi")]
        [InlineData(48, "keturiasdešimt aštuoni")]
        [InlineData(50, "penkiasdešimt")]
        [InlineData(51, "penkiasdešimt vienas")]
        [InlineData(55, "penkiasdešimt penki")]
        [InlineData(59, "penkiasdešimt devyni")]
        [InlineData(60, "šešiasdešimt")]
        [InlineData(61, "šešiasdešimt vienas")]
        [InlineData(62, "šešiasdešimt du")]
        [InlineData(66, "šešiasdešimt šeši")]
        [InlineData(70, "septyniasdešimt")]
        [InlineData(71, "septyniasdešimt vienas")]
        [InlineData(73, "septyniasdešimt trys")]
        [InlineData(77, "septyniasdešimt septyni")]
        [InlineData(80, "aštuoniasdešimt")]
        [InlineData(81, "aštuoniasdešimt vienas")]
        [InlineData(84, "aštuoniasdešimt keturi")]
        [InlineData(88, "aštuoniasdešimt aštuoni")]
        [InlineData(90, "devyniasdešimt")]
        [InlineData(91, "devyniasdešimt vienas")]
        [InlineData(95, "devyniasdešimt penki")]
        [InlineData(99, "devyniasdešimt devyni")]
        [InlineData(100, "šimtas")]
        [InlineData(101, "šimtas vienas")]
        [InlineData(105, "šimtas penki")]
        [InlineData(110, "šimtas dešimt")]
        [InlineData(151, "šimtas penkiasdešimt vienas")]
        [InlineData(200, "du šimtai")]
        [InlineData(202, "du šimtai du")]
        [InlineData(206, "du šimtai šeši")]
        [InlineData(220, "du šimtai dvidešimt")]
        [InlineData(262, "du šimtai šešiasdešimt du")]
        [InlineData(300, "trys šimtai")]
        [InlineData(303, "trys šimtai trys")]
        [InlineData(307, "trys šimtai septyni")]
        [InlineData(330, "trys šimtai trisdešimt")]
        [InlineData(373, "trys šimtai septyniasdešimt trys")]
        [InlineData(400, "keturi šimtai")]
        [InlineData(404, "keturi šimtai keturi")]
        [InlineData(408, "keturi šimtai aštuoni")]
        [InlineData(440, "keturi šimtai keturiasdešimt")]
        [InlineData(484, "keturi šimtai aštuoniasdešimt keturi")]
        [InlineData(500, "penki šimtai")]
        [InlineData(505, "penki šimtai penki")]
        [InlineData(509, "penki šimtai devyni")]
        [InlineData(550, "penki šimtai penkiasdešimt")]
        [InlineData(595, "penki šimtai devyniasdešimt penki")]
        [InlineData(600, "šeši šimtai")]
        [InlineData(601, "šeši šimtai vienas")]
        [InlineData(606, "šeši šimtai šeši")]
        [InlineData(616, "šeši šimtai šešiolika")]
        [InlineData(660, "šeši šimtai šešiasdešimt")]
        [InlineData(700, "septyni šimtai")]
        [InlineData(702, "septyni šimtai du")]
        [InlineData(707, "septyni šimtai septyni")]
        [InlineData(727, "septyni šimtai dvidešimt septyni")]
        [InlineData(770, "septyni šimtai septyniasdešimt")]
        [InlineData(800, "aštuoni šimtai")]
        [InlineData(803, "aštuoni šimtai trys")]
        [InlineData(808, "aštuoni šimtai aštuoni")]
        [InlineData(838, "aštuoni šimtai trisdešimt aštuoni")]
        [InlineData(880, "aštuoni šimtai aštuoniasdešimt")]
        [InlineData(900, "devyni šimtai")]
        [InlineData(904, "devyni šimtai keturi")]
        [InlineData(909, "devyni šimtai devyni")]
        [InlineData(949, "devyni šimtai keturiasdešimt devyni")]
        [InlineData(990, "devyni šimtai devyniasdešimt")]
        [InlineData(1000, "tūkstantis")]
        [InlineData(1001, "tūkstantis vienas")]
        [InlineData(1012, "tūkstantis dvylika")]
        [InlineData(1100, "tūkstantis šimtas")]
        [InlineData(1234, "tūkstantis du šimtai trisdešimt keturi")]
        [InlineData(2000, "du tūkstančiai")]
        [InlineData(2002, "du tūkstančiai du")]
        [InlineData(2023, "du tūkstančiai dvidešimt trys")]
        [InlineData(2345, "du tūkstančiai trys šimtai keturiasdešimt penki")]
        [InlineData(3000, "trys tūkstančiai")]
        [InlineData(3003, "trys tūkstančiai trys")]
        [InlineData(3034, "trys tūkstančiai trisdešimt keturi")]
        [InlineData(3456, "trys tūkstančiai keturi šimtai penkiasdešimt šeši")]
        [InlineData(4000, "keturi tūkstančiai")]
        [InlineData(4004, "keturi tūkstančiai keturi")]
        [InlineData(4045, "keturi tūkstančiai keturiasdešimt penki")]
        [InlineData(4567, "keturi tūkstančiai penki šimtai šešiasdešimt septyni")]
        [InlineData(5000, "penki tūkstančiai")]
        [InlineData(5005, "penki tūkstančiai penki")]
        [InlineData(5056, "penki tūkstančiai penkiasdešimt šeši")]
        [InlineData(5678, "penki tūkstančiai šeši šimtai septyniasdešimt aštuoni")]
        [InlineData(6000, "šeši tūkstančiai")]
        [InlineData(6006, "šeši tūkstančiai šeši")]
        [InlineData(6067, "šeši tūkstančiai šešiasdešimt septyni")]
        [InlineData(6789, "šeši tūkstančiai septyni šimtai aštuoniasdešimt devyni")]
        [InlineData(7000, "septyni tūkstančiai")]
        [InlineData(7007, "septyni tūkstančiai septyni")]
        [InlineData(7078, "septyni tūkstančiai septyniasdešimt aštuoni")]
        [InlineData(7890, "septyni tūkstančiai aštuoni šimtai devyniasdešimt")]
        [InlineData(8000, "aštuoni tūkstančiai")]
        [InlineData(8008, "aštuoni tūkstančiai aštuoni")]
        [InlineData(8089, "aštuoni tūkstančiai aštuoniasdešimt devyni")]
        [InlineData(8901, "aštuoni tūkstančiai devyni šimtai vienas")]
        [InlineData(9000, "devyni tūkstančiai")]
        [InlineData(9009, "devyni tūkstančiai devyni")]
        [InlineData(9012, "devyni tūkstančiai dvylika")]
        [InlineData(9090, "devyni tūkstančiai devyniasdešimt")]
        [InlineData(10000, "dešimt tūkstančių")]
        [InlineData(10001, "dešimt tūkstančių vienas")]
        [InlineData(20020, "dvidešimt tūkstančių dvidešimt")]
        [InlineData(30300, "trisdešimt tūkstančių trys šimtai")]
        [InlineData(31955, "trisdešimt vienas tūkstantis devyni šimtai penkiasdešimt penki")]
        [InlineData(44000, "keturiasdešimt keturi tūkstančiai")]
        [InlineData(44231, "keturiasdešimt keturi tūkstančiai du šimtai trisdešimt vienas")]
        [InlineData(100000, "šimtas tūkstančių")]
        [InlineData(500000, "penki šimtai tūkstančių")]
        [InlineData(1000000, "milijonas")]
        [InlineData(6000000, "šeši milijonai")]
        [InlineData(10000000, "dešimt milijonų")]
        [InlineData(70000000, "septyniasdešimt milijonų")]
        [InlineData(100000000, "šimtas milijonų")]
        [InlineData(800000000, "aštuoni šimtai milijonų")]
        [InlineData(2147483647, "du milijardai šimtas keturiasdešimt septyni milijonai keturi šimtai aštuoniasdešimt trys tūkstančiai šeši šimtai keturiasdešimt septyni")]
        [InlineData(9223372036854775807, "devyni kvintilijonai du šimtai dvidešimt trys kvadrilijonai trys šimtai septyniasdešimt du trilijonai trisdešimt šeši milijardai aštuoni šimtai penkiasdešimt keturi milijonai septyni šimtai septyniasdešimt penki tūkstančiai aštuoni šimtai septyni")]
        public void ToWords(long number, string expected)
        {
            Assert.Equal(expected, number.ToWords());
        }

        [Theory]
        [InlineData(0, "nulinis")]
        [InlineData(21, "dvidešimt pirmas")]
        [InlineData(22, "dvidešimt antras")]
        [InlineData(26, "dvidešimt šeštas")]
        [InlineData(30, "trisdešimtasis")]
        [InlineData(31, "trisdešimt pirmas")]
        [InlineData(33, "trisdešimt trečias")]
        [InlineData(37, "trisdešimt septintas")]
        [InlineData(40, "keturiasdešimtasis")]
        [InlineData(41, "keturiasdešimt pirmas")]
        [InlineData(44, "keturiasdešimt ketvirtas")]
        [InlineData(48, "keturiasdešimt aštuntas")]
        [InlineData(50, "penkiasdešimtasis")]
        [InlineData(51, "penkiasdešimt pirmas")]
        [InlineData(55, "penkiasdešimt penktas")]
        [InlineData(59, "penkiasdešimt devintas")]
        [InlineData(60, "šešiasdešimtasis")]
        [InlineData(61, "šešiasdešimt pirmas")]
        [InlineData(62, "šešiasdešimt antras")]
        [InlineData(66, "šešiasdešimt šeštas")]
        [InlineData(70, "septyniasdešimtasis")]
        [InlineData(71, "septyniasdešimt pirmas")]
        [InlineData(73, "septyniasdešimt trečias")]
        [InlineData(77, "septyniasdešimt septintas")]
        [InlineData(80, "aštuoniasdešimtasis")]
        [InlineData(81, "aštuoniasdešimt pirmas")]
        [InlineData(84, "aštuoniasdešimt ketvirtas")]
        [InlineData(88, "aštuoniasdešimt aštuntas")]
        [InlineData(90, "devyniasdešimtasis")]
        [InlineData(91, "devyniasdešimt pirmas")]
        [InlineData(95, "devyniasdešimt penktas")]
        [InlineData(99, "devyniasdešimt devintas")]
        [InlineData(100, "šimtasis")]
        [InlineData(101, "šimtas pirmas")]
        [InlineData(105, "šimtas penktas")]
        [InlineData(110, "šimtas dešimtasis")]
        [InlineData(151, "šimtas penkiasdešimt pirmas")]
        [InlineData(200, "du šimtasis")]
        [InlineData(202, "du šimtai antras")]
        [InlineData(206, "du šimtai šeštas")]
        [InlineData(220, "du šimtai dvidešimtasis")]
        [InlineData(262, "du šimtai šešiasdešimt antras")]
        [InlineData(300, "trys šimtasis")]
        [InlineData(303, "trys šimtai trečias")]
        [InlineData(307, "trys šimtai septintas")]
        [InlineData(330, "trys šimtai trisdešimtasis")]
        [InlineData(373, "trys šimtai septyniasdešimt trečias")]
        [InlineData(400, "keturi šimtasis")]
        [InlineData(404, "keturi šimtai ketvirtas")]
        [InlineData(408, "keturi šimtai aštuntas")]
        [InlineData(440, "keturi šimtai keturiasdešimtasis")]
        [InlineData(484, "keturi šimtai aštuoniasdešimt ketvirtas")]
        [InlineData(500, "penki šimtasis")]
        [InlineData(505, "penki šimtai penktas")]
        [InlineData(509, "penki šimtai devintas")]
        [InlineData(550, "penki šimtai penkiasdešimtasis")]
        [InlineData(595, "penki šimtai devyniasdešimt penktas")]
        [InlineData(600, "šeši šimtasis")]
        [InlineData(601, "šeši šimtai pirmas")]
        [InlineData(606, "šeši šimtai šeštas")]
        [InlineData(616, "šeši šimtai šešioliktas")]
        [InlineData(660, "šeši šimtai šešiasdešimtasis")]
        [InlineData(700, "septyni šimtasis")]
        [InlineData(702, "septyni šimtai antras")]
        [InlineData(707, "septyni šimtai septintas")]
        [InlineData(727, "septyni šimtai dvidešimt septintas")]
        [InlineData(770, "septyni šimtai septyniasdešimtasis")]
        [InlineData(800, "aštuoni šimtasis")]
        [InlineData(803, "aštuoni šimtai trečias")]
        [InlineData(808, "aštuoni šimtai aštuntas")]
        [InlineData(838, "aštuoni šimtai trisdešimt aštuntas")]
        [InlineData(880, "aštuoni šimtai aštuoniasdešimtasis")]
        [InlineData(900, "devyni šimtasis")]
        [InlineData(904, "devyni šimtai ketvirtas")]
        [InlineData(909, "devyni šimtai devintas")]
        [InlineData(949, "devyni šimtai keturiasdešimt devintas")]
        [InlineData(990, "devyni šimtai devyniasdešimtasis")]
        [InlineData(1000, "tūkstantasis")]
        [InlineData(1001, "tūkstantis pirmas")]
        [InlineData(1012, "tūkstantis dvyliktas")]
        [InlineData(1100, "tūkstantis šimtasis")]
        [InlineData(1234, "tūkstantis du šimtai trisdešimt ketvirtas")]
        [InlineData(2000, "du tūkstantasis")]
        [InlineData(2002, "du tūkstančiai antras")]
        [InlineData(2023, "du tūkstančiai dvidešimt trečias")]
        [InlineData(2345, "du tūkstančiai trys šimtai keturiasdešimt penktas")]
        [InlineData(3000, "trys tūkstantasis")]
        [InlineData(3003, "trys tūkstančiai trečias")]
        [InlineData(3034, "trys tūkstančiai trisdešimt ketvirtas")]
        [InlineData(3456, "trys tūkstančiai keturi šimtai penkiasdešimt šeštas")]
        [InlineData(4000, "keturi tūkstantasis")]
        [InlineData(4004, "keturi tūkstančiai ketvirtas")]
        [InlineData(4045, "keturi tūkstančiai keturiasdešimt penktas")]
        [InlineData(4567, "keturi tūkstančiai penki šimtai šešiasdešimt septintas")]
        [InlineData(5000, "penki tūkstantasis")]
        [InlineData(5005, "penki tūkstančiai penktas")]
        [InlineData(5056, "penki tūkstančiai penkiasdešimt šeštas")]
        [InlineData(5678, "penki tūkstančiai šeši šimtai septyniasdešimt aštuntas")]
        [InlineData(6000, "šeši tūkstantasis")]
        [InlineData(6006, "šeši tūkstančiai šeštas")]
        [InlineData(6067, "šeši tūkstančiai šešiasdešimt septintas")]
        [InlineData(6789, "šeši tūkstančiai septyni šimtai aštuoniasdešimt devintas")]
        [InlineData(7000, "septyni tūkstantasis")]
        [InlineData(7007, "septyni tūkstančiai septintas")]
        [InlineData(7078, "septyni tūkstančiai septyniasdešimt aštuntas")]
        [InlineData(7890, "septyni tūkstančiai aštuoni šimtai devyniasdešimtasis")]
        [InlineData(8000, "aštuoni tūkstantasis")]
        [InlineData(8008, "aštuoni tūkstančiai aštuntas")]
        [InlineData(8089, "aštuoni tūkstančiai aštuoniasdešimt devintas")]
        [InlineData(8901, "aštuoni tūkstančiai devyni šimtai pirmas")]
        [InlineData(9000, "devyni tūkstantasis")]
        [InlineData(9009, "devyni tūkstančiai devintas")]
        [InlineData(9012, "devyni tūkstančiai dvyliktas")]
        [InlineData(9090, "devyni tūkstančiai devyniasdešimtasis")]
        [InlineData(10000, "dešimt tūkstantasis")]
        [InlineData(10001, "dešimt tūkstančių pirmas")]
        [InlineData(20020, "dvidešimt tūkstančių dvidešimtasis")]
        [InlineData(30300, "trisdešimt tūkstančių trys šimtasis")]
        [InlineData(44000, "keturiasdešimt keturi tūkstantasis")]
        [InlineData(44231, "keturiasdešimt keturi tūkstančiai du šimtai trisdešimt pirmas")]
        [InlineData(100000, "šimtas tūkstantasis")]
        [InlineData(500000, "penki šimtai tūkstantasis")]
        [InlineData(1000000, "milijonasis")]
        [InlineData(6000000, "šeši milijonasis")]
        [InlineData(10000000, "dešimt milijonasis")]
        [InlineData(70000000, "septyniasdešimt milijonasis")]
        [InlineData(100000000, "šimtas milijonasis")]
        [InlineData(800000000, "aštuoni šimtai milijonasis")]
        public void ToOrdinalWordsMasculine(int number, string expected)
        {
            Assert.Equal(expected, number.ToOrdinalWords(GrammaticalGender.Masculine));
        }

        [Theory]
        [InlineData(0, "nulinė")]
        [InlineData(21, "dvidešimt pirma")]
        [InlineData(22, "dvidešimt antra")]
        [InlineData(26, "dvidešimt šešta")]
        [InlineData(30, "trisdešimtoji")]
        [InlineData(31, "trisdešimt pirma")]
        [InlineData(33, "trisdešimt trečia")]
        [InlineData(37, "trisdešimt septinta")]
        [InlineData(40, "keturiasdešimtoji")]
        [InlineData(41, "keturiasdešimt pirma")]
        [InlineData(44, "keturiasdešimt ketvirta")]
        [InlineData(48, "keturiasdešimt aštunta")]
        [InlineData(50, "penkiasdešimtoji")]
        [InlineData(51, "penkiasdešimt pirma")]
        [InlineData(55, "penkiasdešimt penkta")]
        [InlineData(59, "penkiasdešimt devinta")]
        [InlineData(60, "šešiasdešimtoji")]
        [InlineData(61, "šešiasdešimt pirma")]
        [InlineData(62, "šešiasdešimt antra")]
        [InlineData(66, "šešiasdešimt šešta")]
        [InlineData(70, "septyniasdešimtoji")]
        [InlineData(71, "septyniasdešimt pirma")]
        [InlineData(73, "septyniasdešimt trečia")]
        [InlineData(77, "septyniasdešimt septinta")]
        [InlineData(80, "aštuoniasdešimtoji")]
        [InlineData(81, "aštuoniasdešimt pirma")]
        [InlineData(84, "aštuoniasdešimt ketvirta")]
        [InlineData(88, "aštuoniasdešimt aštunta")]
        [InlineData(90, "devyniasdešimtoji")]
        [InlineData(91, "devyniasdešimt pirma")]
        [InlineData(95, "devyniasdešimt penkta")]
        [InlineData(99, "devyniasdešimt devinta")]
        [InlineData(100, "šimtoji")]
        [InlineData(101, "šimtas pirma")]
        [InlineData(105, "šimtas penkta")]
        [InlineData(110, "šimtas dešimtoji")]
        [InlineData(151, "šimtas penkiasdešimt pirma")]
        [InlineData(200, "du šimtoji")]
        [InlineData(202, "du šimtai antra")]
        [InlineData(206, "du šimtai šešta")]
        [InlineData(220, "du šimtai dvidešimtoji")]
        [InlineData(262, "du šimtai šešiasdešimt antra")]
        [InlineData(300, "trys šimtoji")]
        [InlineData(303, "trys šimtai trečia")]
        [InlineData(307, "trys šimtai septinta")]
        [InlineData(330, "trys šimtai trisdešimtoji")]
        [InlineData(373, "trys šimtai septyniasdešimt trečia")]
        [InlineData(400, "keturi šimtoji")]
        [InlineData(404, "keturi šimtai ketvirta")]
        [InlineData(408, "keturi šimtai aštunta")]
        [InlineData(440, "keturi šimtai keturiasdešimtoji")]
        [InlineData(484, "keturi šimtai aštuoniasdešimt ketvirta")]
        [InlineData(500, "penki šimtoji")]
        [InlineData(505, "penki šimtai penkta")]
        [InlineData(509, "penki šimtai devinta")]
        [InlineData(550, "penki šimtai penkiasdešimtoji")]
        [InlineData(595, "penki šimtai devyniasdešimt penkta")]
        [InlineData(600, "šeši šimtoji")]
        [InlineData(601, "šeši šimtai pirma")]
        [InlineData(606, "šeši šimtai šešta")]
        [InlineData(616, "šeši šimtai šešiolikta")]
        [InlineData(660, "šeši šimtai šešiasdešimtoji")]
        [InlineData(700, "septyni šimtoji")]
        [InlineData(702, "septyni šimtai antra")]
        [InlineData(707, "septyni šimtai septinta")]
        [InlineData(727, "septyni šimtai dvidešimt septinta")]
        [InlineData(770, "septyni šimtai septyniasdešimtoji")]
        [InlineData(800, "aštuoni šimtoji")]
        [InlineData(803, "aštuoni šimtai trečia")]
        [InlineData(808, "aštuoni šimtai aštunta")]
        [InlineData(838, "aštuoni šimtai trisdešimt aštunta")]
        [InlineData(880, "aštuoni šimtai aštuoniasdešimtoji")]
        [InlineData(900, "devyni šimtoji")]
        [InlineData(904, "devyni šimtai ketvirta")]
        [InlineData(909, "devyni šimtai devinta")]
        [InlineData(949, "devyni šimtai keturiasdešimt devinta")]
        [InlineData(990, "devyni šimtai devyniasdešimtoji")]
        [InlineData(1000, "tūkstantoji")]
        [InlineData(1001, "tūkstantis pirma")]
        [InlineData(1012, "tūkstantis dvylikta")]
        [InlineData(1100, "tūkstantis šimtoji")]
        [InlineData(1234, "tūkstantis du šimtai trisdešimt ketvirta")]
        [InlineData(2000, "du tūkstantoji")]
        [InlineData(2002, "du tūkstančiai antra")]
        [InlineData(2023, "du tūkstančiai dvidešimt trečia")]
        [InlineData(2345, "du tūkstančiai trys šimtai keturiasdešimt penkta")]
        [InlineData(3000, "trys tūkstantoji")]
        [InlineData(3003, "trys tūkstančiai trečia")]
        [InlineData(3034, "trys tūkstančiai trisdešimt ketvirta")]
        [InlineData(3456, "trys tūkstančiai keturi šimtai penkiasdešimt šešta")]
        [InlineData(4000, "keturi tūkstantoji")]
        [InlineData(4004, "keturi tūkstančiai ketvirta")]
        [InlineData(4045, "keturi tūkstančiai keturiasdešimt penkta")]
        [InlineData(4567, "keturi tūkstančiai penki šimtai šešiasdešimt septinta")]
        [InlineData(5000, "penki tūkstantoji")]
        [InlineData(5005, "penki tūkstančiai penkta")]
        [InlineData(5056, "penki tūkstančiai penkiasdešimt šešta")]
        [InlineData(5678, "penki tūkstančiai šeši šimtai septyniasdešimt aštunta")]
        [InlineData(6000, "šeši tūkstantoji")]
        [InlineData(6006, "šeši tūkstančiai šešta")]
        [InlineData(6067, "šeši tūkstančiai šešiasdešimt septinta")]
        [InlineData(6789, "šeši tūkstančiai septyni šimtai aštuoniasdešimt devinta")]
        [InlineData(7000, "septyni tūkstantoji")]
        [InlineData(7007, "septyni tūkstančiai septinta")]
        [InlineData(7078, "septyni tūkstančiai septyniasdešimt aštunta")]
        [InlineData(7890, "septyni tūkstančiai aštuoni šimtai devyniasdešimtoji")]
        [InlineData(8000, "aštuoni tūkstantoji")]
        [InlineData(8008, "aštuoni tūkstančiai aštunta")]
        [InlineData(8089, "aštuoni tūkstančiai aštuoniasdešimt devinta")]
        [InlineData(8901, "aštuoni tūkstančiai devyni šimtai pirma")]
        [InlineData(9000, "devyni tūkstantoji")]
        [InlineData(9009, "devyni tūkstančiai devinta")]
        [InlineData(9012, "devyni tūkstančiai dvylikta")]
        [InlineData(9090, "devyni tūkstančiai devyniasdešimtoji")]
        [InlineData(10000, "dešimt tūkstantoji")]
        [InlineData(10001, "dešimt tūkstančių pirma")]
        [InlineData(20020, "dvidešimt tūkstančių dvidešimtoji")]
        [InlineData(30300, "trisdešimt tūkstančių trys šimtoji")]
        [InlineData(44000, "keturiasdešimt keturi tūkstantoji")]
        [InlineData(44231, "keturiasdešimt keturi tūkstančiai du šimtai trisdešimt pirma")]
        [InlineData(100000, "šimtas tūkstantoji")]
        [InlineData(500000, "penki šimtai tūkstantoji")]
        [InlineData(1000000, "milijonoji")]
        [InlineData(6000000, "šeši milijonoji")]
        [InlineData(10000000, "dešimt milijonoji")]
        [InlineData(70000000, "septyniasdešimt milijonoji")]
        [InlineData(100000000, "šimtas milijonoji")]
        [InlineData(800000000, "aštuoni šimtai milijonoji")]
        public void ToOrdinalWordsFeminine(int number, string expected)
        {
            Assert.Equal(expected, number.ToOrdinalWords(GrammaticalGender.Feminine));
        }
    }
}
