public interface IResources
{
    public string Culture { get; }
    public string DateSingleSecondAgo { get; }
    public string DateMultipleSecondsAgo { get; }
    public string DateSingleMinuteAgo { get; }
    public string DateMultipleMinutesAgo { get; }
    public string DateSingleHourAgo { get; }
    public string DateMultipleHoursAgo { get; }
    public string DateSingleDayAgo { get; }
    public string DateMultipleDaysAgo { get; }
    public string DateSingleMonthAgo { get; }
    public string DateMultipleMonthsAgo { get; }
    public string DateSingleYearAgo { get; }
    public string DateMultipleYearsAgo { get; }
    public string TimeSpanMultipleDays { get; }
    public string TimeSpanMultipleHours { get; }
    public string TimeSpanMultipleMilliseconds { get; }
    public string TimeSpanMultipleMinutes { get; }
    public string TimeSpanMultipleSeconds { get; }
    public string TimeSpanSingleDay { get; }
    public string TimeSpanSingleHour { get; }
    public string TimeSpanSingleMillisecond { get; }
    public string TimeSpanSingleMinute { get; }
    public string TimeSpanSingleSecond { get; }
    public string TimeSpanZero { get; }
    public string TimeSpanMultipleWeeks { get; }
    public string TimeSpanSingleWeek { get; }
    public string DateMultipleDaysFromNow { get; }
    public string DateMultipleHoursFromNow { get; }
    public string DateMultipleMinutesFromNow { get; }
    public string DateMultipleMonthsFromNow { get; }
    public string DateMultipleSecondsFromNow { get; }
    public string DateMultipleYearsFromNow { get; }
    public string DateNow { get; }
    public string DateSingleDayFromNow { get; }
    public string DateSingleHourFromNow { get; }
    public string DateSingleMinuteFromNow { get; }
    public string DateSingleMonthFromNow { get; }
    public string DateSingleSecondFromNow { get; }
    public string DateSingleYearFromNow { get; }
    public string DateMultipleHoursFromNowDual { get; }
    public string DateMultipleMinutesFromNowPlural { get; }
    public string DateMultipleSecondsAgoDual { get; }
    public string DateMultipleSecondsFromNowDual { get; }
    public string DateMultipleYearsFromNowDual { get; }
    public string TimeSpanMultipleDaysDual { get; }
    public string TimeSpanMultipleDaysPlural { get; }
    public string TimeSpanMultipleHoursPlural { get; }
    public string TimeSpanMultipleMillisecondsDual { get; }
    public string TimeSpanMultipleMinutesDual { get; }
    public string TimeSpanMultipleMinutesPlural { get; }
    public string TimeSpanMultipleSecondsPlural { get; }
    public string TimeSpanMultipleMillisecondsPlural { get; }
    public string DateMultipleDaysAgoDual { get; }
    public string DateMultipleDaysAgoPlural { get; }
    public string DateMultipleDaysAgoSingular { get; }
    public string DateMultipleDaysFromNowDual { get; }
    public string DateMultipleDaysFromNowPlural { get; }
    public string DateMultipleDaysFromNowSingular { get; }
    public string DateMultipleHoursAgoDual { get; }
    public string DateMultipleHoursAgoPlural { get; }
    public string DateMultipleHoursAgoSingular { get; }
    public string DateMultipleHoursFromNowPlural { get; }
    public string DateMultipleHoursFromNowSingular { get; }
    public string DateMultipleMinutesAgoDual { get; }
    public string DateMultipleMinutesAgoPlural { get; }
    public string DateMultipleMinutesAgoSingular { get; }
    public string DateMultipleMinutesFromNowDual { get; }
    public string DateMultipleMinutesFromNowSingular { get; }
    public string DateMultipleMonthsAgoDual { get; }
    public string DateMultipleMonthsAgoPlural { get; }
    public string DateMultipleMonthsAgoSingular { get; }
    public string DateMultipleMonthsFromNowDual { get; }
    public string DateMultipleMonthsFromNowPlural { get; }
    public string DateMultipleMonthsFromNowSingular { get; }
    public string DateMultipleSecondsAgoPlural { get; }
    public string DateMultipleSecondsAgoSingular { get; }
    public string DateMultipleSecondsFromNowPlural { get; }
    public string DateMultipleSecondsFromNowSingular { get; }
    public string DateMultipleYearsAgoDual { get; }
    public string DateMultipleYearsAgoPlural { get; }
    public string DateMultipleYearsAgoSingular { get; }
    public string DateMultipleYearsFromNowPlural { get; }
    public string DateMultipleYearsFromNowSingular { get; }
    public string TimeSpanMultipleDaysSingular { get; }
    public string TimeSpanMultipleHoursDual { get; }
    public string TimeSpanMultipleHoursSingular { get; }
    public string TimeSpanMultipleMillisecondsSingular { get; }
    public string TimeSpanMultipleMinutesSingular { get; }
    public string TimeSpanMultipleSecondsDual { get; }
    public string TimeSpanMultipleSecondsSingular { get; }
    public string TimeSpanMultipleWeeksDual { get; }
    public string TimeSpanMultipleWeeksPlural { get; }
    public string TimeSpanMultipleWeeksSingular { get; }
    public string TimeSpanMultipleMonths { get; }
    public string TimeSpanMultipleYears { get; }
    public string TimeSpanSingleMonth { get; }
    public string TimeSpanSingleYear { get; }
    public string DateNever { get; }
    public string TimeSpanMultipleMonthsDual { get; }
    public string TimeSpanMultipleMonthsPlural { get; }
    public string TimeSpanMultipleMonthsSingular { get; }
    public string TimeSpanMultipleYearsDual { get; }
    public string TimeSpanMultipleYearsPlural { get; }
    public string TimeSpanMultipleYearsSingular { get; }
    public string TimeSpanSingleDayWords { get; }
    public string TimeSpanSingleHourWords { get; }
    public string TimeSpanSingleMillisecondWords { get; }
    public string TimeSpanSingleMinuteWords { get; }
    public string TimeSpanSingleMonthWords { get; }
    public string TimeSpanSingleSecondWords { get; }
    public string TimeSpanSingleWeekWords { get; }
    public string TimeSpanSingleYearWords { get; }
    public string N { get; }
    public string NNE { get; }
    public string NE { get; }
    public string ENE { get; }
    public string E { get; }
    public string ESE { get; }
    public string SE { get; }
    public string SSE { get; }
    public string S { get; }
    public string SSW { get; }
    public string SW { get; }
    public string WSW { get; }
    public string W { get; }
    public string WNW { get; }
    public string NW { get; }
    public string NNW { get; }
    public string NShort { get; }
    public string NNEShort { get; }
    public string NEShort { get; }
    public string ENEShort { get; }
    public string EShort { get; }
    public string ESEShort { get; }
    public string SEShort { get; }
    public string SSEShort { get; }
    public string SShort { get; }
    public string SSWShort { get; }
    public string SWShort { get; }
    public string WSWShort { get; }
    public string WShort { get; }
    public string WNWShort { get; }
    public string NWShort { get; }
    public string NNWShort { get; }
    public string DataUnitBit { get; }
    public string DataUnitBitSymbol { get; }
    public string DataUnitByte { get; }
    public string DataUnitByteSymbol { get; }
    public string DataUnitKilobyte { get; }
    public string DataUnitKilobyteSymbol { get; }
    public string DataUnitMegabyte { get; }
    public string DataUnitMegabyteSymbol { get; }
    public string DataUnitGigabyte { get; }
    public string DataUnitGigabyteSymbol { get; }
    public string DataUnitTerabyte { get; }
    public string DataUnitTerabyteSymbol { get; }
    public string TimeUnitMillisecond { get; }
    public string TimeUnitSecond { get; }
    public string TimeUnitMinute { get; }
    public string TimeUnitHour { get; }
    public string TimeUnitDay { get; }
    public string TimeUnitWeek { get; }
    public string TimeUnitMonth { get; }
    public string TimeUnitYear { get; }
    public string DateMultipleDaysAgoPaucal { get; }
    public string DateMultipleDaysFromNowPaucal { get; }
    public string DateMultipleHoursAgoPaucal { get; }
    public string DateMultipleHoursFromNowPaucal { get; }
    public string DateMultipleMinutesAgoPaucal { get; }
    public string DateMultipleMinutesFromNowPaucal { get; }
    public string DateMultipleMonthsAgoPaucal { get; }
    public string DateMultipleMonthsFromNowPaucal { get; }
    public string DateMultipleSecondsAgoPaucal { get; }
    public string DateMultipleSecondsFromNowPaucal { get; }
    public string DateMultipleYearsAgoPaucal { get; }
    public string DateMultipleYearsFromNowPaucal { get; }
    public string DateTwoDaysAgo { get; }
    public string DateTwoDaysFromNow { get; }
    public string TimeSpanMultipleDaysPaucal { get; }
    public string TimeSpanMultipleHoursPaucal { get; }
    public string TimeSpanMultipleMillisecondsPaucal { get; }
    public string TimeSpanMultipleMinutesPaucal { get; }
    public string TimeSpanMultipleMonthsPaucal { get; }
    public string TimeSpanMultipleSecondsPaucal { get; }
    public string TimeSpanMultipleWeeksPaucal { get; }
    public string TimeSpanMultipleYearsPaucal { get; }
    public string TimeSpanAge { get; }
}
