using System;
using System.Collections.Generic;
using System.Collections.Immutable;

namespace Humanizer.SourceGenerators;

public sealed partial class HumanizerSourceGenerator
{
    /// <summary>
    /// Defines the structural generator contracts in typed C# so locale YAML remains the only
    /// checked-in data authoring surface. These schemas mirror the canonical <c>surfaces</c>
    /// layout and intentionally live beside the factories that consume them.
    /// </summary>
    static class EngineContractCatalog
    {
        public static ImmutableDictionary<string, EngineContract> NumberToWords { get; } = CreateNumberToWordsSchemas();
        public static ImmutableDictionary<string, EngineContract> TimeOnlyToClockNotation { get; } = CreateTimeOnlyToClockNotationSchemas();

        static EngineContract Schema(string engineName, string? runtimeType, params EngineContractMember[] members) =>
            new(engineName, runtimeType, members.ToImmutableArray());

        static EngineContractMember Member(
            string kind,
            string? sourcePath = null,
            string? typeName = null,
            string? enumType = null,
            string? builder = null,
            string? defaultValue = null,
            string? fallbackSourcePath = null,
            string? missingValue = null,
            params EngineContractMember[] members) =>
            new(kind, sourcePath, typeName, enumType, builder, defaultValue, fallbackSourcePath, missingValue, members.ToImmutableArray());

        static ImmutableDictionary<string, EngineContract> CreateNumberToWordsSchemas() =>
            new Dictionary<string, EngineContract>(StringComparer.Ordinal)
            {
                ["agglutinative-ordinal-scale"] = Schema("agglutinative-ordinal-scale", null,
                Member("profile-object", null, null, null, null, null, null, null,
                            Member("string", "minusWord", null, null, null, null, null, null),
                            Member("string", "tensSuffix", null, null, null, null, null, null),
                            Member("string", "teenSuffix", null, null, null, null, null, null),
                            Member("string", "ordinalTensSuffix", null, null, null, null, null, null),
                            Member("string-array", "unitsMap", null, null, null, null, null, null),
                            Member("string-array", "ordinalUnitsMap", null, null, null, null, null, null),
                            Member("builder", "scales", null, null, "agglutinative-ordinal-scale-array", null, null, null),
                            Member("nullable-int-string-dictionary", "ordinalExceptions", null, null, null, null, null, "empty")
                        )
            ),
                ["appended-group"] = Schema("appended-group", null,
                Member("profile-object", null, null, null, null, null, null, null,
                            Member("string", "zeroWord", null, null, null, null, null, null),
                            Member("string", "negativeWord", null, null, null, null, null, null),
                            Member("string", "conjunctionWord", null, null, null, null, null, null),
                            Member("string", "ordinalZeroWord", null, null, null, null, null, null),
                            Member("string", "ordinalSeparatorWord", null, null, null, null, null, null),
                            Member("string", "ordinalPrefix", null, null, null, null, null, null),
                            Member("string", "firstOrdinalMasculine", null, null, null, null, null, null),
                            Member("string", "firstOrdinalFeminine", null, null, null, null, null, null),
                            Member("string-array", "groups", null, null, null, null, null, null),
                            Member("string-array", "appendedGroups", null, null, null, null, null, null),
                            Member("string-array", "pluralGroups", null, null, null, null, null, null),
                            Member("string-array", "onesGroup", null, null, null, null, null, null),
                            Member("string-array", "tensGroup", null, null, null, null, null, null),
                            Member("string-array", "hundredsGroup", null, null, null, null, null, null),
                            Member("string-array", "appendedTwos", null, null, null, null, null, null),
                            Member("string-array", "twos", null, null, null, null, null, null),
                            Member("string-array", "feminineOnesGroup", null, null, null, null, null, null),
                            Member("string-string-dictionary", "ordinalExceptions", null, null, null, null, null, null),
                            Member("string-string-dictionary", "feminineOrdinalExceptions", null, null, null, null, null, null)
                        )
            ),
                // Shared engine for locales whose main split is billion-scale naming plus ordinal/cardinal separator policy. The schema stays structural: one nested cardinal section, one nested ordinal section.
                ["billion-strategy"] = Schema("billion-strategy", null,
                Member("profile-object", null, null, null, null, null, null, null,
                            Member("string", "minusWord", null, null, null, null, null, null),
                            Member("string", "andWord", null, null, null, null, null, null),
                            Member("profile-object", "cardinal", null, null, null, null, null, null,
                                        Member("string", "hundredExactWord", null, null, null, null, null, null),
                                        Member("string", "thousandWord", null, null, null, null, null, null),
                                        Member("string", "millionSingularWord", null, null, null, null, null, null),
                                        Member("string", "millionPluralWord", null, null, null, null, null, null),
                                        Member("enum", "billionStrategy", null, "BillionCardinalStrategy", null, null, null, null),
                                        Member("nullable-string", "billionSingularWord", null, null, null, null, null, null),
                                        Member("nullable-string", "billionPluralWord", null, null, null, null, null, null),
                                        Member("string-array", "unitsMap", null, null, null, null, null, null),
                                        Member("string-array", "tensMap", null, null, null, null, null, null),
                                        Member("string-array", "hundredsMap", null, null, null, null, null, null)
                                    ),
                            Member("profile-object", "ordinal", null, null, null, null, null, null,
                                        Member("enum", "billionStrategy", null, "BillionOrdinalStrategy", null, null, null, null),
                                        Member("string", "thousandWord", null, null, null, null, null, null),
                                        Member("string", "millionWord", null, null, null, null, null, null),
                                        Member("nullable-string", "billionWord", null, null, null, null, null, null),
                                        Member("enum", "millionJoinMode", null, "BillionOrdinalMillionJoinMode", null, "spaced", null, null),
                                        Member("string-array", "unitsMap", null, null, null, null, null, null),
                                        Member("string-array", "tensMap", null, null, null, null, null, null),
                                        Member("string-array", "hundredsMap", null, null, null, null, null, null)
                                    )
                        )
            ),
                ["conjoined-gendered-scale"] = Schema("conjoined-gendered-scale", "ConjoinedGenderedScaleNumberToWordsConverter",
                Member("profile-object", null, null, null, null, null, null, null,
                            Member("string", "minusWord", null, null, null, null, null, null),
                            Member("string", "conjunction", null, null, null, null, null, null),
                            Member("string-array", "unitsMap", null, null, null, null, null, null),
                            Member("string-array", "tensMap", null, null, null, null, null, null),
                            Member("string-array", "hundredsMap", null, null, null, null, null, null),
                            Member("string-array", "hundredsOrdinalMap", null, null, null, null, null, null),
                            Member("string-array", "unitsOrdinal", null, null, null, null, null, null),
                            Member("builder", "scales", null, null, "conjoined-gendered-scale-array", null, null, null)
                        )
            ),
                // Shared scale-decomposition engine for locales whose main variability is conjunction placement, ordinal naming, and scale metadata. Locale-owned YAML provides the words and strategy enums; the runtime kernel stays generic.
                ["conjunctional-scale"] = Schema("conjunctional-scale", null,
                Member("profile-object", null, null, null, null, null, null, null,
                            Member("string", "minusWord", null, null, null, null, null, null),
                            Member("string", "andWord", null, null, null, null, null, null),
                            Member("string", "hundredWord", null, null, null, null, null, null),
                            Member("string", "hundredOrdinalWord", null, null, null, null, null, null),
                            Member("string", "tensUnitsSeparator", null, null, null, null, null, null),
                            Member("bool", "defaultAddAnd", null, null, null, null, null, null),
                            Member("enum", "addAndMode", null, "ConjunctionalScaleAddAndMode", null, null, null, null),
                            Member("enum", "andStrategy", null, "ConjunctionalScaleAndStrategy", null, null, null, null),
                            Member("string", "tupleSuffix", null, null, null, null, null, null),
                            Member("enum", "ordinalLeadingOneStrategy", null, "ConjunctionalScaleOrdinalLeadingOneStrategy", null, null, null, null),
                            Member("enum", "ordinalMode", null, "ConjunctionalScaleOrdinalMode", null, null, null, null),
                            Member("string-array", "unitsMap", null, null, null, null, null, null),
                            Member("string-array", "ordinalUnitsMap", null, null, null, null, null, null),
                            Member("string-array", "tensMap", null, null, null, null, null, null),
                            Member("string-array", "ordinalTensMap", null, null, null, null, null, null),
                            Member("builder", "scales", null, null, "conjunctional-scale-array", null, null, null),
                            Member("nullable-int-string-dictionary", "namedTuples", null, null, null, null, null, null)
                        )
            ),
                ["construct-state-scale"] = Schema("construct-state-scale", null,
                Member("profile-object", null, null, null, null, null, null, null,
                            Member("enum", "defaultGender", null, "GrammaticalGender", null, null, null, null),
                            Member("string", "zeroWord", null, null, null, null, null, null),
                            Member("string", "minusWord", null, null, null, null, null, null),
                            Member("string", "andPrefix", null, null, null, null, null, null),
                            Member("string", "teenMasculineWord", null, null, null, null, null, null),
                            Member("string", "teenFeminineWord", null, null, null, null, null, null),
                            Member("string", "teenNormalizationOld", null, null, null, null, null, null),
                            Member("string", "teenNormalizationNew", null, null, null, null, null, null),
                            Member("string-array", "unitsFeminine", null, null, null, null, null, null),
                            Member("string-array", "unitsMasculine", null, null, null, null, null, null),
                            Member("string-array", "tensMap", null, null, null, null, null, null),
                            Member("string", "oneHundredWord", null, null, null, null, null, null),
                            Member("string", "twoHundredsWord", null, null, null, null, null, null),
                            Member("string", "hundredsPluralSuffix", null, null, null, null, null, null),
                            Member("string", "thousandsPluralSuffix", null, null, null, null, null, null),
                            Member("string", "thousandsSingularSuffix", null, null, null, null, null, null),
                            Member("nullable-int-string-dictionary", "thousandsSpecialCases", null, null, null, null, null, "empty"),
                            Member("builder", "scales", null, null, "construct-state-scale-array", null, null, null)
                        ),
                Member("culture", null, null, null, null, null, null, null)
            ),
                ["contextual-decimal"] = Schema("contextual-decimal", null,
                Member("profile-object", null, null, null, null, null, null, null,
                            Member("string", "zeroWord", null, null, null, null, null, null),
                            Member("string", "minusWord", null, null, null, null, null, null),
                            Member("string", "ordinalPrefix", null, null, null, null, null, null),
                            Member("string", "tenWord", null, null, null, null, null, null),
                            Member("string", "tensWord", null, null, null, null, null, null),
                            Member("string", "zeroTensWord", null, null, null, null, null, null),
                            Member("string-array", "digitWords", null, null, null, null, null, null),
                            Member("builder", "scales", null, null, "contextual-decimal-scale-array", null, null, null),
                            Member("nullable-int-string-dictionary", "teenUnitExceptions", null, null, null, null, null, "empty"),
                            Member("nullable-int-string-dictionary", "postTensUnitExceptions", null, null, null, null, null, "empty"),
                            Member("nullable-int-string-dictionary", "exactOrdinals", null, null, null, null, null, "empty")
                        )
            ),
                // Shared engine for locales that contract 'one + scale' into a dedicated scale word such as 'seratus' or 'seribu'. Locale-owned YAML provides the lexical rows; the algorithm stays shared.
                ["contracted-one-scale"] = Schema("contracted-one-scale", null,
                Member("profile-object", null, null, null, null, null, null, null,
                            Member("string", "zeroWord", null, null, null, null, null, null),
                            Member("string", "minusWord", null, null, null, null, null, null),
                            Member("string", "hundredWord", null, null, null, null, null, null),
                            Member("string", "hundredUnitWord", null, null, null, null, null, null),
                            Member("string-array", "units", null, null, null, null, null, null),
                            Member("string-array", "tens", null, null, null, null, null, null),
                            Member("builder", "scales", null, null, "contracted-one-scale-array", null, null, null)
                        )
            ),
                ["east-asian-grouped"] = Schema("east-asian-grouped", null,
                Member("profile-object", null, null, null, null, null, null, null,
                            Member("string", "zeroWord", null, null, null, null, null, null),
                            Member("string", "negativePrefix", null, null, null, null, null, null),
                            Member("string", "ordinalPrefix", null, null, null, "", null, null),
                            Member("string", "ordinalSuffix", null, null, null, "", null, null),
                            Member("string-array", "digitWords", null, null, null, null, null, null),
                            Member("string-array", "smallUnitWords", null, null, null, null, null, null),
                            Member("string-array", "largeUnits", null, null, null, null, null, null),
                            Member("bool", "omitOneBeforeTen", null, null, null, null, null, null),
                            Member("bool", "omitOneBeforeTenOnlyWhenLeading", null, null, null, null, null, null),
                            Member("bool", "omitOneBeforeHundred", null, null, null, null, null, null),
                            Member("bool", "omitOneBeforeThousand", null, null, null, null, null, null),
                            Member("bool", "insertZeroInGroup", null, null, null, null, null, null),
                            Member("bool", "insertZeroBetweenGroups", null, null, null, null, null, null),
                            Member("nullable-int-string-dictionary", "ordinalMap", null, null, null, null, null, null)
                        )
            ),
                ["east-slavic"] = Schema("east-slavic", null,
                Member("profile-object", null, null, null, null, null, null, null,
                            Member("string", "zeroWord", null, null, null, null, null, null),
                            Member("string", "minusWord", null, null, null, null, null, null),
                            Member("string", "zeroOrdinalStem", null, null, null, null, null, null),
                            Member("string-array", "hundredsMap", null, null, null, null, null, null),
                            Member("string-array", "tensMap", null, null, null, null, null, null),
                            Member("string-array", "unitsMap", null, null, null, null, null, null),
                            Member("string-array", "unitsOrdinalPrefixes", null, null, null, null, null, null),
                            Member("string-array", "tensOrdinalPrefixes", null, null, null, null, null, null),
                            Member("string-array", "tensOrdinal", null, null, null, null, null, null),
                            Member("string-array", "unitsOrdinal", null, null, null, null, null, null),
                            Member("string", "feminineOne", null, null, null, null, null, null),
                            Member("string", "neuterOne", null, null, null, null, null, null),
                            Member("string", "feminineTwo", null, null, null, null, null, null),
                            Member("string", "oneOrdinalPrefix", null, null, null, "одно", null, null),
                            Member("builder", "scales", null, null, "east-slavic-scale-array", null, null, null),
                            Member("builder", "endings.masculine", null, null, "east-slavic-gender-ending", null, null, null),
                            Member("builder", "endings.feminine", null, null, "east-slavic-gender-ending", null, null, null),
                            Member("builder", "endings.neuter", null, null, "east-slavic-gender-ending", null, null, null)
                        )
            ),
                ["gendered-scale-ordinal"] = Schema("gendered-scale-ordinal", null,
                Member("profile-object", null, null, null, null, null, null, null,
                            Member("string", "zeroWord", null, null, null, null, null, null),
                            Member("string", "minusWord", null, null, null, null, null, null),
                            Member("string", "feminineSingular", null, null, null, null, null, null),
                            Member("string", "masculineOrdinalPrefix", null, null, null, null, null, null),
                            Member("string", "feminineOrdinalPrefix", null, null, null, null, null, null),
                            Member("string", "masculineOrdinalSuffix", null, null, null, null, null, null),
                            Member("string", "feminineOrdinalSuffix", null, null, null, null, null, null),
                            Member("string", "joinGroups", null, null, null, null, null, null),
                            Member("string", "joinAboveTwenty", null, null, null, null, null, null),
                            Member("string-array", "unitsVariants", null, null, null, null, null, null),
                            Member("string-array", "teensVariants", null, null, null, null, null, null),
                            Member("string-array", "tensMap", null, null, null, null, null, null),
                            Member("string-array", "ordinalUnderTenVariants", null, null, null, null, null, null),
                            Member("builder", "scales", null, null, "gendered-scale-ordinal-array", null, null, null)
                        )
            ),
                // Shared decimal-scale engine for locales whose ordinal behavior is driven by harmony or final-character suffix selection. The schema models the reusable suffix system directly instead of naming a language family.
                ["harmony-ordinal"] = Schema("harmony-ordinal", null,
                Member("profile-object", null, null, null, null, null, null, null,
                            Member("int64", "minimumValue", null, null, null, null, null, null),
                            Member("int64", "maximumValue", null, null, null, null, null, null),
                            Member("string", "minusWord", null, null, null, null, null, null),
                            Member("string", "hundredWord", null, null, null, null, null, null),
                            Member("enum", "hundredStrategy", null, "HarmonyOrdinalHundredStrategy", null, null, null, null),
                            Member("string-array", "unitsMap", null, null, null, null, null, null),
                            Member("string-array", "tensMap", null, null, null, null, null, null),
                            Member("builder", "scales", null, null, "harmony-ordinal-scale-array", null, null, null),
                            Member("enum", "ordinalSuffixStrategy", null, "HarmonyOrdinalSuffixStrategy", null, null, null, null),
                            Member("bool", "softenTerminalTBeforeSuffix", null, null, null, null, null, null),
                            Member("bool", "dropTerminalVowelBeforeHarmonySuffix", null, null, null, null, null, null),
                            Member("nullable-char-string-dictionary", "ordinalSuffixes", null, null, null, null, null, null),
                            Member("nullable-string", "secondOrdinalSuffixCharacters", null, null, null, null, null, null),
                            Member("optional-string-array", "ordinalSuffixPair", null, null, null, null, null, null),
                            Member("nullable-char-string-dictionary", "tupleSuffixes", null, null, null, null, null, null),
                            Member("nullable-int-string-dictionary", "namedTuples", null, null, null, null, null, null)
                        )
            ),
                ["hyphenated-scale"] = Schema("hyphenated-scale", "HyphenatedScaleNumberToWordsConverter",
                Member("profile-object", null, null, null, null, null, null, null,
                            Member("string", "zeroWord", null, null, null, null, null, null),
                            Member("string", "zeroOrdinalWord", null, null, null, null, null, null),
                            Member("string", "minusWord", null, null, null, null, null, null),
                            Member("string", "twoPrefixWord", null, null, null, null, null, null),
                            Member("string-array", "unitsMap", null, null, null, null, null, null),
                            Member("string-array", "ordinalUnitsMap", null, null, null, null, null, null),
                            Member("string-array", "tensMap", null, null, null, null, null, null),
                            Member("string-array", "ordinalTensMap", null, null, null, null, null, null),
                            Member("string-array", "hundredsMap", null, null, null, null, null, null),
                            Member("nullable-int-string-dictionary", "ordinalUnitsExceptions", null, null, null, null, null, "empty"),
                            Member("nullable-int-string-dictionary", "wholeTensExceptions", null, null, null, null, null, "empty"),
                            Member("builder", "scales", null, null, "hyphenated-scale-array", null, null, null),
                            Member("builder", "thousandScale", null, null, "hyphenated-scale", null, null, null),
                            Member("nullable-int-string-dictionary", "tupleMap", null, null, null, null, null, "empty")
                        )
            ),
                ["hyphenated-ordinal"] = Schema("hyphenated-ordinal", null,
                Member("profile-object", null, null, null, null, null, null, null,
                            Member("string", "zeroWord", null, null, null, null, null, null),
                            Member("string", "negativeWord", null, null, null, null, null, null),
                            Member("string", "thousandWord", null, null, null, null, null, null),
                            Member("string", "millionSingularPrefix", null, null, null, null, null, null),
                            Member("string", "millionSingular", null, null, null, null, null, null),
                            Member("string", "millionPlural", null, null, null, null, null, null),
                            Member("string", "masculineCompoundOne", null, null, null, null, null, null),
                            Member("string", "feminineCompoundOne", null, null, null, null, null, null),
                            Member("string", "masculineOrdinalOne", null, null, null, null, null, null),
                            Member("string", "feminineOrdinalOne", null, null, null, null, null, null),
                            Member("string", "defaultTensJoiner", null, null, null, null, null, null),
                            Member("string", "specialTensJoiner", null, null, null, null, null, null),
                            Member("int32", "specialJoinerTensValue", null, null, null, null, null, null),
                            Member("string", "masculineTensOrdinalSuffix", null, null, null, null, null, null),
                            Member("string", "feminineTensOrdinalSuffix", null, null, null, null, null, null),
                            Member("string", "masculineOrdinalAppender", null, null, null, null, null, null),
                            Member("string", "defaultOrdinalAbbreviationMasculine", null, null, null, null, null, null),
                            Member("string", "defaultOrdinalAbbreviationFeminine", null, null, null, null, null, null),
                            Member("string", "tupleFallbackWord", null, null, null, null, null, null),
                            Member("string-array", "unitsMasculine", null, null, null, null, null, null),
                            Member("string-array", "unitsFeminine", null, null, null, null, null, null),
                            Member("string-array", "teens", null, null, null, null, null, null),
                            Member("string-array", "tens", null, null, null, null, null, null),
                            Member("string-array", "hundredsMasculine", null, null, null, null, null, null),
                            Member("string-array", "hundredsFeminine", null, null, null, null, null, null),
                            Member("string-array", "ordinalMasculine", null, null, null, null, null, null),
                            Member("string-array", "ordinalFeminine", null, null, null, null, null, null),
                            Member("string-array", "ordinalTensStems", null, null, null, null, null, null),
                            Member("string-array", "ordinalUnitComponents", null, null, null, null, null, null),
                            Member("string-array", "tupleMap", null, null, null, null, null, null),
                            Member("string-string-dictionary", "ordinalAbbreviations", null, null, null, null, null, null)
                        )
            ),
                ["indian-grouping"] = Schema("indian-grouping", null,
                Member("profile-object", null, null, null, null, null, null, null,
                            Member("string", "zeroWord", null, null, null, null, null, null),
                            Member("string", "negativeWord", null, null, null, null, null, null),
                            Member("string", "ordinalSuffix", null, null, null, null, null, null),
                            Member("string", "quintillionWord", null, null, null, null, null, null),
                            Member("string", "quadrillionWord", null, null, null, null, null, null),
                            Member("string", "lakhWord", null, null, null, null, null, null),
                            Member("string", "singleLakhWord", null, null, null, null, null, null),
                            Member("string", "croreWord", null, null, null, null, null, null),
                            Member("string", "defaultTensWithRemainderSuffix", null, null, null, null, null, null),
                            Member("string", "specialTensWithRemainderSuffix", null, null, null, null, null, null),
                            Member("string", "nineTensWithRemainderSuffix", null, null, null, null, null, null),
                            Member("string", "exactTensDefaultSuffix", null, null, null, null, null, null),
                            Member("string", "exactTensNineSuffix", null, null, null, null, null, null),
                            Member("string", "exactThousandsDefaultSuffix", null, null, null, null, null, null),
                            Member("string", "exactThousandsNineSuffix", null, null, null, null, null, null),
                            Member("string", "thousandContinuingSuffix", null, null, null, null, null, null),
                            Member("string", "thousandExactSuffix", null, null, null, null, null, null),
                            Member("string", "thousandsOneBridge", null, null, null, null, null, null),
                            Member("string", "lakhContinuingSuffix", null, null, null, null, null, null),
                            Member("string", "lakhExactSuffix", null, null, null, null, null, null),
                            Member("string", "croreContinuingSuffix", null, null, null, null, null, null),
                            Member("string", "hundredsContinuingSuffix", null, null, null, null, null, null),
                            Member("string", "hundredsExactSuffix", null, null, null, null, null, null),
                            Member("string", "hundredsNineContinuingSuffix", null, null, null, null, null, null),
                            Member("string", "hundredsNineExactSuffix", null, null, null, null, null, null),
                            Member("string-array", "unitsMap", null, null, null, null, null, null),
                            Member("string-array", "tensMap", null, null, null, null, null, null),
                            Member("string-array", "hundredsMap", null, null, null, null, null, null),
                            Member("string-array", "thousandsMap", null, null, null, null, null, null),
                            Member("nullable-int-string-dictionary", "ordinalExceptions", null, null, null, null, null, "empty")
                        )
            ),
                ["inverted-tens"] = Schema("inverted-tens", null,
                Member("profile-object", null, null, null, null, null, null, null,
                            Member("string", "minusWord", null, null, null, null, null, null),
                            Member("string-array", "unitsMap", null, null, null, null, null, null),
                            Member("string-array", "tensMap", null, null, null, null, null, null),
                            Member("string-array", "hundredsPrefixMap", null, null, null, null, null, null),
                            Member("string", "oneHundredWord", null, null, null, null, null, null),
                            Member("string", "hundredWord", null, null, null, null, null, null),
                            Member("string", "hundredJoiner", null, null, null, "", null, null),
                            Member("string", "hundredRemainderSeparator", null, null, null, "", null, null),
                            Member("string", "scaleTailPrefix", null, null, null, "", null, null),
                            Member("enum", "scaleTailPrefixMode", null, "InvertedTensTailPrefixMode", null, "none", null, null),
                            Member("string", "hundredTailPrefix", null, null, null, "", null, null),
                            Member("enum", "hundredTailPrefixMode", null, "InvertedTensTailPrefixMode", null, "none", null, null),
                            Member("string", "unitTensJoiner", null, null, null, null, null, null),
                            Member("string", "unitTensAlternateJoinerUnitEnding", null, null, null, "", null, null),
                            Member("string", "unitTensAlternateJoiner", null, null, null, null, "unitTensJoiner", null),
                            Member("builder", "scales", null, null, "inverted-tens-scale-array", null, null, null),
                            Member("enum", "ordinalMode", null, "InvertedTensOrdinalMode", null, "suffix", null, null),
                            Member("nullable-string-string-dictionary", "ordinalExceptions", null, null, null, null, null, "empty"),
                            Member("string", "ordinalSteSuffixEndingChars", null, null, null, "", null, null),
                            Member("string", "ordinalSteSuffix", null, null, null, "", null, null),
                            Member("string", "ordinalDefaultSuffix", null, null, null, "", null, null),
                            Member("bool", "removeLeadingOneInOrdinal", null, null, null, null, null, null),
                            Member("string", "leadingOneWord", null, null, null, "", null, null),
                            Member("string", "leadingOnePreservePrefix", null, null, null, "", null, null)
                        )
            ),
                ["joined-scale"] = Schema("joined-scale", null,
                Member("profile-object", null, null, null, null, null, null, null,
                            Member("int64", "maximumValue", null, null, null, null, null, null),
                            Member("string", "zeroWord", null, null, null, null, null, null),
                            Member("string", "minusWord", null, null, null, null, null, null),
                            Member("string", "negativeJoinWord", null, null, null, " ", null, null),
                            Member("string", "joinWord", null, null, null, "", null, null),
                            Member("string", "scaleCountJoinWord", null, null, null, " ", null, null),
                            Member("string", "underHundredJoinWord", null, null, null, "", "joinWord", null),
                            Member("bool", "omitOneWhenSingularAlways", null, null, null, null, null, null),
                            Member("string", "defaultOrdinalSuffix", null, null, null, "", null, null),
                            Member("nullable-string", "matchingOrdinalSuffix", null, null, null, null, null, null),
                            Member("nullable-string", "ordinalSuffixMatchCharacters", null, null, null, null, null, null),
                            Member("optional-string-array", "unitsMap", null, null, null, null, null, null),
                            Member("optional-string-array", "tensMap", null, null, null, null, null, null),
                            Member("string-array", "hundredsMap", null, null, null, null, null, null),
                            Member("optional-string-array", "subHundredMap", null, null, null, null, null, null),
                            Member("builder", "scales", null, null, "joined-scale-array", null, null, null),
                            Member("nullable-int-string-dictionary", "ordinalExceptions", null, null, null, null, null, null),
                            Member("nullable-int64", "compoundOrdinalRemainder", null, null, null, null, null, null),
                            Member("nullable-string", "compoundOrdinalWord", null, null, null, null, null, null),
                            Member("nullable-int-set", "compoundOrdinalExcludedValues", null, null, null, null, null, null)
                        )
            ),
                ["linking-scale"] = Schema("linking-scale", null,
                Member("profile-object", null, null, null, null, null, null, null,
                            Member("string", "zeroWord", null, null, null, null, null, null),
                            Member("string", "minusWord", null, null, null, null, null, null),
                            Member("string", "conjunctionWord", null, null, null, null, null, null),
                            Member("string", "tensRemainderJoiner", null, null, null, null, null, null),
                            Member("string-array", "unitsMap", null, null, null, null, null, null),
                            Member("string-array", "tensMap", null, null, null, null, null, null),
                            Member("string-array", "hundredWords", null, null, null, null, null, null),
                            Member("string-array", "scalePrefixes", null, null, null, null, null, null),
                            Member("builder", "scales", null, null, "linking-scale-array", null, null, null),
                            Member("builder", "scaleLinkRules", null, null, "linking-suffix-rule-array", null, null, null)
                        )
            ),
                ["long-scale-stem-ordinal"] = Schema("long-scale-stem-ordinal", null,
                Member("profile-object", null, null, null, null, null, null, null,
                            Member("string", "zeroWord", null, null, null, null, null, null),
                            Member("string", "negativeWord", null, null, null, null, null, null),
                            Member("string", "exactHundredWord", null, null, null, null, null, null),
                            Member("string", "thousandWord", null, null, null, null, null, null),
                            Member("string", "tensJoiner", null, null, null, null, null, null),
                            Member("string", "thousandOrdinalStem", null, null, null, null, null, null),
                            Member("string", "masculineOrdinalEnding", null, null, null, null, null, null),
                            Member("string", "feminineOrdinalEnding", null, null, null, null, null, null),
                            Member("string", "minLongValueWord", null, null, null, null, null, null),
                            Member("int64", "highestScaleValue", null, null, null, null, null, null),
                            Member("int32", "roundHigherScaleCompactValue", null, null, null, null, null, null),
                            Member("string", "highestScaleOrdinalSource", null, null, null, null, null, null),
                            Member("string", "highestScaleOrdinalTarget", null, null, null, null, null, null),
                            Member("string", "tupleFallbackSuffix", null, null, null, null, null, null),
                            Member("string-array", "hundredsMasculine", null, null, null, null, null, null),
                            Member("string-array", "hundredsFeminine", null, null, null, null, null, null),
                            Member("string-array", "hundredthsRoots", null, null, null, null, null, null),
                            Member("string-array", "ordinalUnitRoots", null, null, null, null, null, null),
                            Member("string-array", "tensMap", null, null, null, null, null, null),
                            Member("string-array", "tenthsRoots", null, null, null, null, null, null),
                            Member("string-array", "thousandthsRoots", null, null, null, null, null, null),
                            Member("string-array", "tupleMap", null, null, null, null, null, null),
                            Member("string-array", "unitsMasculine", null, null, null, null, null, null),
                            Member("string-array", "unitsMasculineAbbreviation", null, null, null, null, null, null),
                            Member("string-array", "unitsFeminine", null, null, null, null, null, null),
                            Member("builder", "largeScales", null, null, "long-scale-word-array", null, null, null)
                        )
            ),
                ["dual-form-scale"] = Schema("dual-form-scale", "DualFormScaleNumberToWordsConverter",
                Member("profile-object", null, null, null, null, null, null, null,
                            Member("string", "conjunction", null, null, null, null, null, null),
                            Member("string", "minusSuffix", null, null, null, null, null, null),
                            Member("string", "feminineOneWord", null, null, null, null, null, null),
                            Member("string", "hundredWord", null, null, null, null, null, null),
                            Member("string", "dualHundredsWord", null, null, null, null, null, null),
                            Member("string", "hundredPrefixWord", null, null, null, null, null, null),
                            Member("nullable-int-string-dictionary", "exactOrdinals", null, null, null, null, null, "empty"),
                            Member("string-array", "unitsMap", null, null, null, null, null, null),
                            Member("string-array", "tensMap", null, null, null, null, null, null),
                            Member("string-array", "hundredsMap", null, null, null, null, null, null),
                            Member("string-array", "prefixMap", null, null, null, null, null, null),
                            Member("builder", "thousandScale", null, null, "dual-form-scale", null, null, null),
                            Member("builder", "millionScale", null, null, "dual-form-scale", null, null, null),
                            Member("builder", "billionScale", null, null, "dual-form-scale", null, null, null),
                            Member("builder", "trillionScale", null, null, "dual-form-scale", null, null, null),
                            Member("builder", "quadrillionScale", null, null, "dual-form-scale", null, null, null),
                            Member("builder", "quintillionScale", null, null, "dual-form-scale", null, null, null)
                        )
            ),
                ["ordinal-prefix-scale"] = Schema("ordinal-prefix-scale", null,
                Member("profile-object", null, null, null, null, null, null, null,
                            Member("enum", "defaultGender", null, "GrammaticalGender", null, "masculine", null, null),
                            Member("string", "minusWord", null, null, null, null, null, null),
                            Member("string", "andWord", null, null, null, null, null, null),
                            Member("string", "masculineOrdinalEnding", null, null, null, "i", null, null),
                            Member("string", "nonMasculineOrdinalEnding", null, null, null, "a", null, null),
                            Member("string-array", "unitsMap", null, null, null, null, null, null),
                            Member("string-array", "masculineUnitsMap", null, null, null, null, null, null),
                            Member("string-array", "feminineUnitsMap", null, null, null, null, null, null),
                            Member("string-array", "neuterUnitsMap", null, null, null, null, null, null),
                            Member("string-array", "tensMap", null, null, null, null, null, null),
                            Member("string-array", "unitsOrdinalPrefixes", null, null, null, null, null, null),
                            Member("string-array", "tensOrdinalPrefixes", null, null, null, null, null, null),
                            Member("string", "hundredSingular", null, null, null, null, null, null),
                            Member("string", "hundredPlural", null, null, null, null, null, null),
                            Member("string", "ordinalTwoMasculine", null, null, null, null, null, null),
                            Member("string", "ordinalTwoFeminine", null, null, null, null, null, null),
                            Member("string", "ordinalTwoNeuter", null, null, null, null, null, null),
                            Member("builder", "scales", null, null, "ordinal-prefix-scale-array", null, null, null)
                        )
            ),
                ["pluralized-scale"] = Schema("pluralized-scale", null,
                Member("profile-object", null, null, null, null, null, null, null,
                            Member("string", "zeroWord", null, null, null, null, null, null),
                            Member("string", "minusWord", null, null, null, null, null, null),
                            Member("string", "zeroOrdinalStem", null, null, null, "nul", null, null),
                            Member("string-array", "unitsMap", null, null, null, null, null, null),
                            Member("string-array", "tensMap", null, null, null, null, null, null),
                            Member("string-array", "hundredsMap", null, null, null, null, null, null),
                            Member("builder", "scales", null, null, "pluralized-scale-array", null, null, null),
                            Member("enum", "formDetector", null, "PluralizedScaleFormDetector", null, null, null, null),
                            Member("enum", "unitVariantStrategy", null, "PluralizedScaleUnitVariantStrategy", null, "none", null, null),
                            Member("enum", "ordinalMode", null, "PluralizedScaleOrdinalMode", null, "numeric-culture", null, null),
                            Member("bool", "supportsNeuter", null, null, null, null, null, null),
                            Member("string", "masculineOrdinalSuffix", null, null, null, "as", null, null),
                            Member("string", "feminineOrdinalSuffix", null, null, null, "a", null, null),
                            Member("optional-string-array", "ordinalUnitsMap", null, null, null, null, null, null),
                            Member("optional-string-array", "ordinalTensMap", null, null, null, null, null, null),
                            Member("optional-string-array", "ordinalHundredsMap", null, null, null, null, null, null)
                        ),
                Member("culture", null, null, null, null, null, null, null)
            ),
                // Shared Scandinavian-style engine where the runtime decomposition is stable but the cardinal and ordinal scale strategies diverge by profile data. Strategy enums name the structural choice, not the locale.
                ["scale-strategy"] = Schema("scale-strategy", null,
                Member("profile-object", null, null, null, null, null, null, null,
                            Member("enum", "cardinalStrategy", null, "ScaleStrategyCardinalMode", null, null, null, null),
                            Member("enum", "ordinalStrategy", null, "ScaleStrategyOrdinalMode", null, null, null, null),
                            Member("int64", "maximumValue", null, null, null, null, null, null),
                            Member("enum", "defaultGender", null, "GrammaticalGender", null, null, null, null),
                            Member("string", "zeroWord", null, null, null, null, null, null),
                            Member("string", "minusWord", null, null, null, null, null, null),
                            Member("string", "oneDefault", null, null, null, null, null, null),
                            Member("string", "oneMasculine", null, null, null, null, null, null),
                            Member("string", "oneFeminine", null, null, null, null, null, null),
                            Member("string", "oneNeuter", null, null, null, null, null, null),
                            Member("string", "tensLinker", null, null, null, "", null, null),
                            Member("string", "largeScaleRemainderJoiner", null, null, null, "", null, null),
                            Member("string", "exactLargeScaleOrdinalSuffix", null, null, null, "", null, null),
                            Member("string", "exactDefaultOrdinalSuffix", null, null, null, "", null, null),
                            Member("string", "tensOrdinalTrimEndCharacters", null, null, null, "", null, null),
                            Member("string", "tensOrdinalSuffix", null, null, null, null, null, null),
                            Member("int32", "shortOrdinalUpperBoundExclusive", null, null, null, null, null, null),
                            Member("string", "shortOrdinalTrimEndCharacters", null, null, null, "", null, null),
                            Member("string", "shortOrdinalTrimmedSuffix", null, null, null, "", null, null),
                            Member("string", "shortOrdinalSuffix", null, null, null, "", null, null),
                            Member("string", "hundredWord", null, null, null, null, null, null),
                            Member("string", "hundredCompositeSingularWord", null, null, null, null, null, null),
                            Member("string", "thousandWord", null, null, null, null, null, null),
                            Member("string", "thousandSingularWord", null, null, null, null, null, null),
                            Member("string", "thousandCompositeSingularWord", null, null, null, null, null, null),
                            Member("string-array", "unitsMap", null, null, null, null, null, null),
                            Member("string-array", "tensMap", null, null, null, null, null, null),
                            Member("string-array", "hundredUnitMap", null, null, null, null, null, null),
                            Member("builder", "scales", null, null, "scandinavian-scale-array", null, null, null),
                            Member("nullable-int-string-dictionary", "ordinalExceptions", null, null, null, null, null, "empty")
                        )
            ),
                ["segmented-scale"] = Schema("segmented-scale", null,
                Member("profile-object", null, null, null, null, null, null, null,
                            Member("int64", "maximumValue", null, null, null, null, null, null),
                            Member("string", "zeroWord", null, null, null, null, null, null),
                            Member("string", "minusWord", null, null, null, null, null, null),
                            Member("string", "teenPrefix", null, null, null, null, null, null),
                            Member("string", "exactOneHundredWord", null, null, null, null, null, null),
                            Member("string-array", "unitsDefault", null, null, null, null, null, null),
                            Member("string-array", "unitsPluralized", null, null, null, null, null, null),
                            Member("string-array", "tensMap", null, null, null, null, null, null),
                            Member("string-array", "hundredsDefault", null, null, null, null, null, null),
                            Member("string-array", "hundredsPluralized", null, null, null, null, null, null),
                            Member("builder", "scales", null, null, "segmented-scale-array", null, null, null),
                            Member("int32", "maximumOrdinal", null, null, null, null, null, null),
                            Member("nullable-int-string-dictionary", "ordinalMap", null, null, null, null, null, "empty")
                        )
            ),
                ["south-slavic-cardinal"] = Schema("south-slavic-cardinal", null,
                Member("profile-object", null, null, null, null, null, null, null,
                            Member("int64", "maximumValue", null, null, null, null, null, null),
                            Member("bool", "allowLongMin", null, null, null, null, null, null),
                            Member("string", "zeroWord", null, null, null, null, null, null),
                            Member("string", "minusWord", null, null, null, null, null, null),
                            Member("enum", "scaleFormDetector", null, "SouthSlavicScaleFormDetector", null, "russian", null, null),
                            Member("enum", "numberComposition", null, "SouthSlavicNumberComposition", null, "direct", null, null),
                            Member("string", "invertedTensLinker", null, null, null, "", null, null),
                            Member("string-array", "unitsMap", null, null, null, null, null, null),
                            Member("string-array", "tensMap", null, null, null, null, null, null),
                            Member("string-array", "hundredsMap", null, null, null, null, null, null),
                            Member("string", "feminineOne", null, null, null, null, null, null),
                            Member("string", "feminineTwo", null, null, null, null, null, null),
                            Member("builder", "scales", null, null, "south-slavic-scale-array", null, null, null)
                        ),
                Member("culture", null, null, null, null, null, null, null)
            ),
                ["terminal-ordinal-scale"] = Schema("terminal-ordinal-scale", null,
                Member("profile-object", null, null, null, null, null, null, null,
                            Member("string", "zeroWord", null, null, null, null, null, null),
                            Member("string", "minusWord", null, null, null, null, null, null),
                            Member("string-array", "unitStems", null, null, null, null, null, null),
                            Member("string-array", "ordinalUnitStems", null, null, null, null, null, null),
                            Member("string-array", "tensMap", null, null, null, null, null, null),
                            Member("string-array", "hundredsExactStems", null, null, null, null, null, null),
                            Member("string", "exactOneHundredCardinal", null, null, null, null, null, null),
                            Member("string", "exactOneHundredAfterHigherScale", null, null, null, null, null, null),
                            Member("string", "oneHundredWithRemainder", null, null, null, null, null, null),
                            Member("string", "hundredsPluralWord", null, null, null, null, null, null),
                            Member("string", "masculineOrdinalSuffix", null, null, null, null, null, null),
                            Member("string", "feminineOrdinalSuffix", null, null, null, null, null, null),
                            Member("builder", "scales", null, null, "terminal-ordinal-scale-array", null, null, null)
                        )
            ),
                ["triad-scale"] = Schema("triad-scale", null,
                Member("profile-object", null, null, null, null, null, null, null,
                            Member("string", "zeroWord", null, null, null, null, null, null),
                            Member("string", "minusWord", null, null, null, null, null, null),
                            Member("string", "feminineOneWord", null, null, null, null, null, null),
                            Member("string", "leadingOneWord", null, null, null, null, null, null),
                            Member("string", "tenWord", null, null, null, null, null, null),
                            Member("string", "tenOrdinalStem", null, null, null, null, null, null),
                            Member("string", "commonOrdinalStem", null, null, null, null, null, null),
                            Member("string", "masculineOrdinalSuffix", null, null, null, null, null, null),
                            Member("string", "feminineOrdinalSuffix", null, null, null, null, null, null),
                            Member("string", "ordinalUnit3RestoredVowel", null, null, null, null, null, null),
                            Member("string", "ordinalUnit6RestoredVowel", null, null, null, null, null, null),
                            Member("string-array", "unitsMap", null, null, null, null, null, null),
                            Member("string-array", "unitsFinalAccent", null, null, null, null, null, null),
                            Member("string-array", "tensMap", null, null, null, null, null, null),
                            Member("string-array", "teensMap", null, null, null, null, null, null),
                            Member("string-array", "hundredsMap", null, null, null, null, null, null),
                            Member("string-array", "ordinalUnderTen", null, null, null, null, null, null),
                            Member("builder", "scales", null, null, "triad-scale-array", null, null, null)
                        )
            ),
                // Shared engine for locales whose compound tens place the unit before the tens word. Locale YAML supplies joiner transforms, scale metadata, and gendered lexical forms.
                ["unit-leading-compound"] = Schema("unit-leading-compound", null,
                Member("profile-object", null, null, null, null, null, null, null,
                            Member("string", "zeroWord", null, null, null, null, null, null),
                            Member("string", "minusWord", null, null, null, null, null, null),
                            Member("string", "masculineOne", null, null, null, null, null, null),
                            Member("string", "feminineOne", null, null, null, null, null, null),
                            Member("string", "neuterOne", null, null, null, null, null, null),
                            Member("nullable-string", "feminineTwo", null, null, null, null, null, null),
                            Member("string", "tensJoiner", null, null, null, null, null, null),
                            Member("enum", "tensJoinerTransform", null, "CompoundTensJoinerTransform", null, "none", null, null),
                            Member("string", "ordinalStemSuffix", null, null, null, "s", null, null),
                            Member("string", "masculineOrdinalEnding", null, null, null, null, null, null),
                            Member("string", "feminineOrdinalEnding", null, null, null, null, null, null),
                            Member("string", "neuterOrdinalEnding", null, null, null, null, null, null),
                            Member("bool", "supportsEifelerRule", null, null, null, null, null, null),
                            Member("string-array", "unitsMap", null, null, null, null, null, null),
                            Member("string-array", "compoundUnitsMap", null, null, null, null, null, null),
                            Member("string-array", "tensMap", null, null, null, null, null, null),
                            Member("string-array", "unitsOrdinal", null, null, null, null, null, null),
                            Member("builder", "scales", null, null, "unit-leading-compound-scale-array", null, null, null)
                        )
            ),
                // Shared engine for locales that differ mainly in how 70/80/90 decades are composed. The runtime kernel stays generic; locale-owned YAML chooses the decade strategy and exact overrides.
                ["variant-decade"] = Schema("variant-decade", null,
                Member("profile-object", null, null, null, null, null, null, null,
                            Member("string", "minusWord", null, null, null, null, null, null),
                            Member("enum", "seventyStrategy", null, "VariantDecadeSeventyStrategy", null, null, null, null),
                            Member("enum", "ninetyStrategy", null, "VariantDecadeNinetyStrategy", null, null, null, null),
                            Member("bool", "specialSeventyOneEnabled", null, null, null, null, null, null),
                            Member("nullable-string", "specialSeventyOneWord", null, null, null, null, null, null),
                            Member("bool", "pluralizeExactEighty", null, null, null, null, null, null),
                            Member("nullable-int-set", "tensUsingEtWhenUnitIsOne", null, null, null, null, null, "empty"),
                            Member("string-array", "tensMap", null, null, null, null, null, null)
                        )
            ),
                ["west-slavic-gendered"] = Schema("west-slavic-gendered", null,
                Member("profile-object", null, null, null, null, null, null, null,
                            Member("string", "minusWord", null, null, null, null, null, null),
                            Member("string-array", "unitsMap", null, null, null, null, null, null),
                            Member("string-array", "tensMap", null, null, null, null, null, null),
                            Member("string-array", "hundredsMap", null, null, null, null, null, null),
                            Member("string-array", "unitsMasculineForms", null, null, null, null, null, null),
                            Member("string-array", "unitsFeminineForms", null, null, null, null, null, null),
                            Member("string-array", "unitsNeuterForms", null, null, null, null, null, null),
                            Member("string-array", "unitsInvariantForms", null, null, null, null, null, null),
                            Member("builder", "thousands", null, null, "west-slavic-scale-forms", null, null, null),
                            Member("builder", "millions", null, null, "west-slavic-scale-forms", null, null, null),
                            Member("builder", "trillions", null, null, "west-slavic-scale-forms", null, null, null),
                            Member("builder", "billions", null, null, "west-slavic-scale-forms", null, null, null)
                        ),
                Member("culture", null, null, null, null, null, null, null)
            ),
            }.ToImmutableDictionary(StringComparer.Ordinal);

        static ImmutableDictionary<string, EngineContract> CreateTimeOnlyToClockNotationSchemas() =>
            new Dictionary<string, EngineContract>(StringComparer.Ordinal)
            {
                ["phrase-clock"] = Schema("phrase-clock", "PhraseClockNotationConverter",
                Member("profile-object", null, null, null, null, null, null, null,
                            Member("enum", "hourMode", null, "PhraseClockHourMode", null, "h12", null, null),
                            Member("enum", "hourGender", null, "GrammaticalGender", null, "masculine", null, null),
                            Member("enum", "minuteGender", null, "GrammaticalGender", null, "masculine", null, null),
                            Member("string", "midnight", null, null, null, "", null, null),
                            Member("string", "midday", null, null, null, "", null, null),
                            Member("string", "min0", null, null, null, "", null, null),
                            Member("string", "min5", null, null, null, "", null, null),
                            Member("string", "min10", null, null, null, "", null, null),
                            Member("string", "min15", null, null, null, "", null, null),
                            Member("string", "min20", null, null, null, "", null, null),
                            Member("string", "min25", null, null, null, "", null, null),
                            Member("string", "min30", null, null, null, "", null, null),
                            Member("string", "min35", null, null, null, "", null, null),
                            Member("string", "min40", null, null, null, "", null, null),
                            Member("string", "min45", null, null, null, "", null, null),
                            Member("string", "min50", null, null, null, "", null, null),
                            Member("string", "min55", null, null, null, "", null, null),
                            Member("string", "defaultTemplate", null, null, null, "", null, null),
                            Member("string", "zeroFiller", null, null, null, "", null, null),
                            Member("string", "earlyMorning", null, null, null, "", null, null),
                            Member("string", "morning", null, null, null, "", null, null),
                            Member("string", "afternoon", null, null, null, "", null, null),
                            Member("string", "night", null, null, null, "", null, null),
                            Member("enum", "dayPeriodPosition", null, "PhraseClockDayPeriodPosition", null, "suffix", null, null),
                            Member("string", "hourZeroWord", null, null, null, "", null, null),
                            Member("string", "hourTwelveWord", null, null, null, "", null, null),
                            Member("string", "hourSuffixSingular", null, null, null, "", null, null),
                            Member("string", "hourSuffixPlural", null, null, null, "", null, null),
                            Member("string", "singularArticle", null, null, null, "", null, null),
                            Member("string", "pluralArticle", null, null, null, "", null, null),
                            Member("bool", "applyEifelerRule", null, null, null, "false", null, null),
                            Member("string", "pastHourTemplate", null, null, null, "", null, null),
                            Member("string", "beforeHalfTemplate", null, null, null, "", null, null),
                            Member("string", "afterHalfTemplate", null, null, null, "", null, null),
                            Member("string", "beforeNextTemplate", null, null, null, "", null, null),
                            Member("string", "minuteSuffixSingular", null, null, null, "", null, null),
                            Member("string", "minuteSuffixPlural", null, null, null, "", null, null)
                        )
            ),
            }.ToImmutableDictionary(StringComparer.Ordinal);

    }

}