name: Benchmark Baseline vs Current

on:
  workflow_dispatch:
    inputs:
      baselineVersion:
        description: 'NuGet version of Humanizer to use for the baseline run'
        required: true
        type: string
        default: '2.14.1'
  pull_request:
    branches:
      - main
    paths:
      - 'src/Humanizer/**'
      - 'src/Benchmarks/**'
      - '.github/workflows/benchmarks-baseline-vs-current.yml'
  push:
    branches:
      - 'copilot/identify-performance-improvements'

jobs:
  benchmark:
    name: Run Benchmarks (${{ matrix.kind }})
    runs-on: ubuntu-latest
    env:
      BASELINE_VERSION: ${{ inputs.baselineVersion || '2.14.1' }}
    strategy:
      matrix:
        kind: [baseline, current]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: global.json
      
      - name: Display run information
        run: |
          echo "## Benchmark Run: ${{ matrix.kind }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Commit SHA:** ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Baseline Version:** ${{ env.BASELINE_VERSION }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Run Type:** ${{ matrix.kind }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
      
      - name: Build Benchmarks (baseline)
        if: matrix.kind == 'baseline'
        run: |
          dotnet build src/Benchmarks/Benchmarks.csproj -c Release \
            /p:UseBaselinePackage=true \
            /p:BaselinePackageVersion=${{ env.BASELINE_VERSION }}
      
      - name: Build Benchmarks (current)
        if: matrix.kind == 'current'
        run: |
          dotnet build src/Benchmarks/Benchmarks.csproj -c Release \
            /p:UseBaselinePackage=false
      
      - name: Run Benchmarks
        run: |
          cd src/Benchmarks
          dotnet bin/Release/net10.0/Benchmarks.dll --filter '*' --exporters fulljson markdown
      
      - name: Append Markdown Results to Summary
        run: |
          # Find all markdown files and append them to the summary
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Benchmark Results (${{ matrix.kind }})" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          for MD in src/Benchmarks/BenchmarkDotNet.Artifacts/results/*-report-github.md; do
            if [ -f "$MD" ]; then
              cat "$MD" >> $GITHUB_STEP_SUMMARY
              echo "" >> $GITHUB_STEP_SUMMARY
            fi
          done
      
      - name: Upload JSON Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: humanizer-bdn-${{ matrix.kind }}-json
          path: src/Benchmarks/BenchmarkDotNet.Artifacts/results/*-report-full.json
          retention-days: 7
      
      - name: Upload All Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: humanizer-bdn-${{ matrix.kind }}-all
          path: src/Benchmarks/BenchmarkDotNet.Artifacts/
          retention-days: 7

  compare:
    name: Compare Baseline vs Current
    runs-on: ubuntu-latest
    needs: benchmark
    env:
      BASELINE_VERSION: ${{ inputs.baselineVersion || '2.14.1' }}
    
    steps:
      - name: Download Baseline JSON
        uses: actions/download-artifact@v4
        with:
          name: humanizer-bdn-baseline-json
          path: baseline
      
      - name: Download Current JSON
        uses: actions/download-artifact@v4
        with:
          name: humanizer-bdn-current-json
          path: current
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.x'
      
      - name: Clone and Build ResultsComparer
        run: |
          git clone --depth 1 https://github.com/dotnet/performance
          dotnet build performance/src/tools/ResultsComparer -c Release
      
      - name: Run ResultsComparer
        run: |
          BASE=$(pwd)/baseline
          DIFF=$(pwd)/current
          
          # Find the ResultsComparer DLL
          DOTNET_PERF=$(find performance/artifacts/bin/ResultsComparer/Release -name "ResultsComparer.dll" | head -n 1)
          
          if [ ! -f "$DOTNET_PERF" ]; then
            echo "Error: ResultsComparer.dll not found"
            exit 1
          fi
          
          # Run comparison with 5% threshold
          dotnet "$DOTNET_PERF" --base "$BASE" --diff "$DIFF" --threshold "5%" > diff.md || true
      
      - name: Append Comparison to Summary
        run: |
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "## Performance Comparison: Baseline vs Current" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Baseline Version:** ${{ env.BASELINE_VERSION }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          if [ -f diff.md ]; then
            cat diff.md >> $GITHUB_STEP_SUMMARY
          else
            echo "⚠️ No comparison results available" >> $GITHUB_STEP_SUMMARY
          fi
      
      - name: Upload Comparison Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: humanizer-bdn-comparison
          path: diff.md
          retention-days: 7
